### ISSUE TITLE
[Monitor mode] airmon-ng fails with this driver

### ISSUE THREAD

**Issue by sagypt** [aircrack-ng/rtl8812au#101]
Hi,
maybe I found a bug.
airmon-ng fails with Alfa Network AWUS036ACH using this driver.

**Comment by aircrack-ng** [comment]
Check out the README.md

**Comment by sagypt** [comment]
I'm sorry but your reply is too short, I don't understand.
I have read README file, but the steps provided don't help me.

I used:
```
ifconfig wlan1 down
iwconfig wlan1 mode monitor
ifconfig wlan1 up
```
... a these work.

But, then, indirectly, I need to use

`airmon-ng start wlan1`

and this fails.



PS: yes, before I used

```
airmon-check
airmon-check kill
```

**Comment by kimocoder** [comment]
airmon-ng check kill
ifconfig wlan1 down
iwconfig wlan1 mode monitor
iwconfig wlan1 txpower 30

simple as that.

**Comment by Jinovas** [comment]
For quick/easy monitor mode, use my script.  The device will go into monitor mode without name change btw. 
https://github.com/Jinovas/iwmon
