### ISSUE TITLE
Rt8188eus


### ISSUE THREAD

**Issue by fubefube** [aircrack-ng/rtl8812au#1018]
don't know where to post it
I have a TP-Link TL725n I'm trying to use on Nethunter but without success, so I'm here to ask if this module works with this adapter, because it uses this RTL-8188EUS chip and I see that this module have support for RTL-8188 EU and FTV, but said nothing about EUS.

**Comment by ZerBea** [comment]
This will work:
https://github.com/kimocoder/realtek_rtwifi/issues/34#issuecomment-1401751927
