### ISSUE TITLE
8812au=8812bu

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/rtl8812au#1025]
was found through experiments that,
8812au driver seems to be compatible with 8812bu

![193858](https://user-images.githubusercontent.com/80609791/205439611-f91a5d61-caab-4fad-9204-002e8b22e6ea.png)

wifislax64-3.2-final

![94414]

**Comment by TheCustomFHD** [comment]
I am interested on how you managed to load this driver on the rtl8812bu variant, as i also have a TP-Link Archer T4U v3, with this chipset.. did you just rename the kernel driver file?

**Comment by ghost** [comment]
> I am interested on how you managed to load this driver on the rtl8812bu variant, as i also have a TP-Link Archer T4U v3, with this chipset.. did you just rename the kernel driver file?

Use wifislax64-3.2-final.iso
It already contains 8812bu driver
