### ISSUE TITLE
No networks found

### ISSUE THREAD

**Issue by LxtteDev** [aircrack-ng/rtl8812au#1076]
I recently installed `v5.6.4.2` with no errors. The adapter shows up in settings but its not finding any networks. I've tried an older version, re-installation, and enabling/disabling secure boot to no avail. I am using an `rtl8812AU 802.11ac`, `Ubuntu 22.04`, and `kernel version 5.19`.

**Comment by Anoncheg1** [comment]
try 285989435a43bad0f6fa7e8d7b2886dca0ee5e46 It works for me.

**Comment by LxtteDev** [comment]
Neither of these worked.

**Comment by LxtteDev** [comment]
I decided to give #1078 a go again this time with a fresh install of the drivers and it worked.
