### ISSUE TITLE
Hangs on kernel 6.7 on archlinux

### ISSUE THREAD

**Issue by cluac7** [aircrack-ng/rtl8812au#1137]
Recently tried switched to kernel 6.7, which is now considered stable. Everything worked fine until I realized I had no internet. Doing anything WiFi related didn't work, and would just cause the whole system to hang in the current TTY, forcing me to switch to a different TTY to continue troubleshooting, or in some cases it didn't even let me let me do that and I had to reboot to continue. Eventually connected an ethernet cable (phone USB tethering to be clear, but handled the same nonetheless) which worked, causing me to believe it's not a NetworkManager issue. NetworkManager would also show as connected to WiFi on boot up, but then causing any traffic over WiFi hangs.

Steps I tried to troubleshoot:
- Restarted networkmanager through systemctl, hung.
- `ping`ed any IP or website when it originally showed as connected on boot, hung
- Ran `ip link` with the network adapter plugged in as I booted, hung
- Opened firefox and tried loading a webpage or opened discord, hung

Tested on both `linux` and `linux-zen` 6.7 by `arch-chroot`ing through a live iso and installing them, same results on both. Eventually switched back to `linux-lqx` which is still on 6.6.12 and everything works fine and I can update the rest of my system as lqx is not even on 6.7 yet.
  

Steps to reproduce:
1. Install this driver
2. Install `linux` 6.7 or `linux-zen` 6.7
3. Plug in rtl8821au wifi adapter (specifically I am using TP-Link archer T2U plus)
4. Reboot system into 6.7 kernel

**Comment by crivasr** [comment]
#1134 Should fix this
