### ISSUE TITLE
Driver limit set wireless regulatory domain

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/rtl8812au#1140]
Hello, 
In kali 2023.4  or wifislax64-3.4-final, rtl8812au-5.6.4.2 Driver install success .  .  . 
But canno set "phy#0" to IN by using command method set wireless regulatory domain
"phy#0" , it is wireless interface network card ( RTL8812AU )

```
$ sudo iw reg set IN
$ iw reg get
global
country IN: DFS-UNSET
	(2402 - 2482 @ 40), (N/A, 30), (N/A)
	(5150 - 5250 @ 80), (N/A, 30), (N/A)
	(5250 - 5350 @ 80), (N/A, 24), (0 ms), DFS
	(5470 - 5725 @ 160), (N/A, 24), (0 ms), DFS
	(5725 - 5875 @ 80), (N/A, 30), (N/A)

phy#0
country 99: DFS-UNSET
        (2402 - 2472 @ 40), (N/A, 20), (N/A)
        (2457 - 2482 @ 40), (N/A, 20), (N/A), PASSIVE-SCAN
        (2474 - 2494 @ 40), (N/A, 20), (N/A), NO-OFDM, PASSIVE-SCAN
        (5140 - 5860 @ 80), (N/A, 30), (N/A), PASSIVE-SCAN

$ iw dev    
phy#0
        Interface wlan0
                ifindex 3
                wdev 0x1
                addr 74:DA:38:ff:ff:ff
                type managed
                channel 2 (2417 MHz), width: 20 MHz, center1: 2417 MHz
                txpower 20.00 dBm
```

Seems be driver limit, canno by command method set wireless regulatory domain !
In normal circumstances, it not like this

I test many USB wireless card, (Insert All RTL8812BU/MT7610/RT5572/3070) have linux  kernel driver
No matter many wireless card inserted
Only display one global regulatory domain
Use command
```
$ iw reg get
global
country 00: DFS-UNSET
        (2402 - 2472 @ 40), (6, 20), (N/A)
        (2457 - 2482 @ 20), (6, 20), (N/A), AUTO-BW, PASSIVE-SCAN
        (2474 - 2494 @ 20), (6, 20), (N/A), NO-OFDM, PASSIVE-SCAN
        (5170 - 5250 @ 80), (6, 20), (N/A), AUTO-BW, PASSIVE-SCAN
        (5250 - 5330 @ 80), (6, 20), (0 ms), DFS, AUTO-BW, PASSIVE-SCAN
        (5490 - 5730 @ 160), (6, 20), (0 ms), DFS, PASSIVE-SCAN
        (5735 - 5835 @ 80), (6, 20), (N/A), PASSIVE-SCAN
        (57240 - 63720 @ 2160), (N/A, 0), (N/A)
```

**Comment by dubhater** [comment]
Is the wireless-regdb package installed? If not, install it and reboot.

**Comment by ghost** [comment]
> Is the wireless-regdb package installed? If not, install it and reboot.

Yeah, wireless-regdb package installed
This issue exists in the wifislax64-3.4 final
Your can try reproducing this issue on KALI LINUX and wifislax64-3.4 final 
If you don't have this issue, maybe my problem
Having LINUX kernel driver RT5572 wireless card is not the case
or RTL8812BU

**Comment by sultanqasim** [comment]
I have the same issue, phy#0 region is stuck at DFS-UNSET even though I'm able to change the global regulatory domain. I'm using Ubuntu 24.04 (pre-release).

**Comment by qh-code** [comment]
OK. So the issue has been closed. But what is the solution?

**Comment by dubhater** [comment]
You could try the ``rtw_country_code`` module parameter.

Or you could try kernel 6.14. It has a driver built-in and it definitely supports ``iw reg set __``.
