### ISSUE TITLE
Error with latest version of Kali 

### ISSUE THREAD

**Issue by Aggelos11** [aircrack-ng/rtl8812au#1165]
Hi! I just upgraded my Kali to 6.8 . I tried both the GitHub drivers and the apt realtek-eel88xxau-dkms. Even though they are successfully installed the adaptor even though it is recognised by the machine it is not operational at all. He cannot see/connect to nearby WiFi networks in neither monitor nor managed mode … please help !
![IMG_9201](https://github.com/aircrack-ng/rtl8812au/assets/62383412/228e0e8e-3953-4017-a8a3-191dfbd2043f)

**Comment by Aggelos11** [comment]
Ok so I found a solution to anyone who still struggles… so the commands to install it and make it work are :
sudo apt-get update
sudo apt get upgrade -y
reboot
sudo apt-get install bc mokutil build-essential libelf-dev linux-headers-`uname -r` 
sudo git clone …( GitHub link )
cd rtl*
sudo git checkout 63cf0b4
sudo make && sudo make install

**Comment by SeiV-K** [comment]
glad that you found the solution. feel free to close the issue if it no longer exists :)

**Comment by cr7pt0pl4gu3** [comment]
@SeiV-K @Aggelos11 I don't think it's a good idea to close this issue. I just wasted 6 hours trying to understand why my Alfa is not working, and apparently it's because of the driver version, the latest one is clearly broken for my card

**Comment by fat-cat-73** [comment]
@Aggelos11 Fantastic! Worked like a charm after spending countless hours trying to fix the broken update. Thank you very much for commenting the fix.

 For anyone who may not know, the install line for should be typed as: 

`sudo apt-get install bc mokutil build-essential libelf-dev linux-headers-$(uname -r)`

**Comment by focabigd** [comment]
guys,i've tried what u've just said,but it still isn't working for me,same problem

**Comment by Aggelos11** [comment]
> guys,i've tried what u've just said,but it still isn't working for me,same problem

Which adaptor do you use ?

**Comment by focabigd** [comment]
awus036ach

**Comment by Aggelos11** [comment]
Hm you must be doing something wrong then . Read the instructions I wrote again

**Comment by focabigd** [comment]
i just found the solution,use an older driver

**Comment by Aggelos11** [comment]
This is exactly what gut checkout does my friend

**Comment by focabigd** [comment]
oh,i'm new into linux
