### ISSUE TITLE
make does not work

### ISSUE THREAD

**Issue by D3f4ult-004** [aircrack-ng/rtl8812au#1178]
#################

I am still learning this will be a big help ty most appreciated

$      _This is 2024.2 kali linux vmware

#################

![Screenshot 2024-07-27 044624](https://github.com/user-attachments/assets/f4cde861-60c3-48ca-b0c5-31e76591c3d0)

**Comment by D3f4ult-004** [comment]
i fixed it my self ty

**Comment by kimocoder** [comment]
Awesome. Beware that RTL8812AU and RTL8821AU is not maintained by linux-wireless / upstream at this point 🥇

**Comment by Aggelos11** [comment]
How did you fix that ?
