### ISSUE TITLE
Can not get injection to work 

### ISSUE THREAD

**Issue by trackmastersteve** [aircrack-ng/rtl8812au#118]
I have tried tho get this to work on Arch on bare metal, as well as Kali in a VM. I have this driver installed on both. 

`sudo aireplay-ng -9 wlp0s4f1u5`
`17:35:20  Trying broadcast probe requests...`
`17:35:21  No Answer...`
`17:35:21  Found 0 APs`

Not sure if I'm doing something wrong. But I've failed to get packet injection working on the AWUS036ACH and AWUS1900 with this driver. Injection tests fail with both dongles and with both OS's.

**Comment by kimocoder** [comment]
which virtual machine software? virtualbox, vmware..?

**Comment by trackmastersteve** [comment]
VirtualBox. But I can't seem to get injection working on Host (Arch Linux) either.

**Comment by kimocoder** [comment]
For some reason injection won't work on Virtualbox, but on other VM software it works again (like VMware).

**Comment by trackmastersteve** [comment]
Ah, ok. But why am I not able to inject using it directly through my host OS (Arch) on bare metal?

**Comment by kimocoder** [comment]
Don't know, don't use that OS. on Kali, injection works fine that's what I know for sure

**Comment by trackmastersteve** [comment]
ok, lol. So do you install this driver through kali repos or directly from git?

**Comment by kimocoder** [comment]
Both works, but the git is more up to date right noe. will push another update to Kali shortly

**Comment by trackmastersteve** [comment]
ok, thank you!

**Comment by kimocoder** [comment]
VirtualBox got injection issue, somewhere. will investigate later. Other VM's should work fine, VMware tested and working.

**Comment by kcdtv** [comment]
Just to say that there is no problem in Arch linux.
 I strongly suspect that you do not kill properly  process like network-manager, wpa-supplicant etc...
