### ISSUE TITLE
Doesn't compile on Kali Linux

### ISSUE THREAD

**Issue by pawscanthack** [aircrack-ng/rtl8812au#1183]
Haven't used this in a while. New version doesn't compile. Anyone know what the last working version was?

**Comment by 0x00-V** [comment]
What's the error you're getting?

**Comment by godylockz** [comment]
This worked fine on latest version of kali 2024.2
https://github.com/aircrack-ng/rtl8812au/issues/1169

**Comment by pawscanthack** [comment]
I solved the problem using:
sudo apt install linux-headers-$(uname -r)
It installed but the driver still isn't working.

**Comment by pawscanthack** [comment]
It installed but the driver still isn't working. The interface is not capturing any traffic. My Panda interface is working fine with the same programs, such as Wifite and hcxdumptools.

**Comment by pawscanthack** [comment]
I installed using:
sudo apt install realtek-rtl88xxau-dkms

Now the interface is working as expected. (Alfa AWUS036ACH)
