### ISSUE TITLE
Help with Installing   AWUS036ACH Driver

### ISSUE THREAD

**Issue by wynscott09** [aircrack-ng/rtl8812au#123]
Trying to run ./dkms-install.sh and I am receiving errors :

root@kali:~/rtl8812au# ./dkms-install.sh
About to run dkms install steps...
Error! DKMS tree already contains: rtl8812au-5.1.5
You cannot add the same module/version combo more than once.
Error! echo
Your kernel headers for kernel 4.13.0-kali1-amd64 cannot be found at
/lib/modules/4.13.0-kali1-amd64/build or /lib/modules/4.13.0-kali1-amd64/source.
Error! echo
Your kernel headers for kernel 4.13.0-kali1-amd64 cannot be found at
/lib/modules/4.13.0-kali1-amd64/build or /lib/modules/4.13.0-kali1-amd64/source.
Finished running dkms install steps.

I would appreciate your help.
Thank you.

**Comment by kimocoder** [comment]
You need to install kernel headers, as described in the README.

apt-get install linux-headers-`uname -r`

**Comment by wynscott09** [comment]
tried to run apt-get install linux-headers-`uname -r` 

root@kali:~/rtl8812au# apt-get install linux-headers-`uname -r`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-headers-4.13.0-kali1-amd64
E: Couldn't find any package by glob 'linux-headers-4.13.0-kali1-amd64'
E: Couldn't find any package by regex 'linux-headers-4.13.0-kali1-amd64'
:(

**Comment by wynscott09** [comment]
I already installed the command below  :
sudo apt-get install build-essential
sudo apt-get install bc

but apt-get install linux-headers-uname -r is not working to me.

**Comment by kimocoder** [comment]
Find package in apt with "apt-cache search linux-headers" or check that your apt actually for any sources with "cat /etc/apt/sources.list" at all

**Comment by wynscott09** [comment]
"cat /etc/apt/sources.list" 

![screenshot from 2018-05-05 12-03-07](https://user-images.githubusercontent.com/36039370/39663101-5eec9966-505c-11e8-9b3f-1fa0578e5d56.png)

**Comment by wynscott09** [comment]
apt-cache search linux-headers

![screenshot from 2018-05-05 12-12-56](https://user-images.githubusercontent.com/36039370/39663164-c9b21c5c-505d-11e8-980d-936b0ca287c6.png)

**Comment by kimocoder** [comment]
Well, can't find the v4.13 [here](https://http.kali.org/kali/pool/main/l/linux/) you should maybe consider upgrading to v4.14 or even v4.15.

**Comment by wynscott09** [comment]
May i know the correct command/procedure for upgrading to v4.15.
really appreciate your help.
Thank you.

**Comment by kimocoder** [comment]
apt-get install linux-image-4.15.0-kali3-amd64

Then reboot into it and follow the README with the "uname -r"  command

**Comment by wynscott09** [comment]
linux-image-4.15.0-kali3-amd64 is already the newest version (4.15.17-1kali1).

**Comment by kcdtv** [comment]
You can also use `(sudo) apt update && (sudo) apt full-upgrade " to update kali linux and it kernel. 
Now that you have the latest kernel installed repeat the installation process, the module will be placed in the correct folder

**Comment by kimocoder** [comment]
You forget to reboot into kernel v4.15. reboot into it and install the headers package.
