### ISSUE TITLE
support WEP

### ISSUE THREAD

**Issue by ZeroChaos-** [aircrack-ng/rtl8812au#129]
WEP is unsupported in client mode

**Comment by kimocoder** [comment]
@ZeroChaos- for the 8812 or the 8814 adapter?

**Comment by ZeroChaos-** [comment]
Both? It presently fails on both in my testing.

**Comment by kimocoder** [comment]
Checking ut tomorrow, haven't really used WEP for some years

**Comment by kimocoder** [comment]
@ZeroChaos- WEP (in client mode) works just fine here? At least using 8814au chipset.
May try the 8812au when it arrives too, since their code (in the same driver) are slighty different

**Comment by kcdtv** [comment]
As expected it worked for me too with chip 8812au:  I am connected right now through a WEP 64 network that i will shut down immediately. :smile_cat:  
![fast](https://user-images.githubusercontent.com/7338484/41821906-d594ebd8-77e7-11e8-820b-c9dd17d06dfd.jpg)
Dropping WEP support in client mode wouldn't be anyway such a lost... ...But it works.

**Comment by kimocoder** [comment]
I was using the v5.1.5 for testing btw. Branches below is not maintained and contains too much problems that they should not be used. 

Moving it all over to the v5.2.20 branch soon which fixes lots more issues.

**Comment by kimocoder** [comment]
WEP tested & working on both 8812, 8814 and 8821 ... open another issue if the problem occurs again, but can't seem to find an issue about it?
