### ISSUE TITLE
Capturing WPA Handshake with rtl8814au

### ISSUE THREAD

**Issue by clayday27** [aircrack-ng/rtl8812au#13]
Currently using a ASUS USB-AC68 that contains rtl8814au chipset. 
Installed rtl8814au drivers with no problems. 
USB devices works perfectly. can connect to networks and be put into monitor mode.
Airodump scans never result in WPA handshakes. Longest scan 2 hours.

Has anyone else seen this issue with the rtl884au chipset?

Currently working on a VM of Kali 4.12 on a Mac

**Comment by kimocoder** [comment]
Will test this issue in few days, as we talked about in our email conversation. Thanks!

**Comment by kimocoder** [comment]
This issue is related to #35 - please use that one which contains more information
