### ISSUE TITLE
alfa awus036ac (RTL8812AU) no monitor mode 

### ISSUE THREAD

**Issue by ld00gster** [aircrack-ng/rtl8812au#133]
Hi have a vmware version of Kali lunix fully updated. the install of this driver was clean. when I try to put this interface in monitor mode, it fails. I am missing something?

root@kali:~# airmon-ng check

Found 3 processes that could cause trouble.
If airodump-ng, aireplay-ng or airtun-ng stops working after
a short period of time, you may want to run 'airmon-ng check kill'

  PID Name
  527 NetworkManager
  602 wpa_supplicant
  631 dhclient

root@kali:~# airmon-ng start wlan0

Found 3 processes that could cause trouble.
If airodump-ng, aireplay-ng or airtun-ng stops working after
a short period of time, you may want to run 'airmon-ng check kill'

  PID Name
  527 NetworkManager
  602 wpa_supplicant
  631 dhclient

PHY	Interface	Driver		Chipset

phy0	wlan0		8812au		Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac WLAN Adapter
cat: /sys/class/ieee80211/phy0/device/net/wlan0mon/type: No such file or directory

Newly created monitor mode interface wlan0mon is *NOT* in monitor mode.
Removing non-monitor wlan0mon interface...

WARNING: unable to start monitor mode, please run "airmon-ng check kill"
root@kali:~# airmon-ng check kill

Killing these processes:

  PID Name
  602 wpa_supplicant
  631 dhclient

root@kali:~# airmon-ng start wlan0

PHY	Interface	Driver		Chipset

phy0	wlan0		8812au		Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac WLAN Adapter
cat: /sys/class/ieee80211/phy0/device/net/wlan0mon/type: No such file or directory

Newly created monitor mode interface wlan0mon is *NOT* in monitor mode.
Removing non-monitor wlan0mon interface...

WARNING: unable to start monitor mode, please run "airmon-ng check kill"
root@kali:~#

**Comment by kimocoder** [comment]
airmon-ng does not work with this driver. read the README om howto pur it into monitor mode.
