### ISSUE TITLE
Error! echo Your kernel headers for kernel 4.14.50-v7+ cannot be found at /lib/modules/4.14.50-v7+/build or /lib/modules/4.14.50-v7+/source.

### ISSUE THREAD

**Issue by zhangshp** [aircrack-ng/rtl8812au#137]
Raspberry Pi model 3b+
Linux raspberrypi 4.14.50-v7+ #1122

**Comment by kimocoder** [comment]
This is not a driver issue, you are missing your kernel-headers package. On RPI, take a look at the README om howto install it.

**Comment by zhangshp** [comment]
thanks ,the rpi kernel headers version 4.14.50-v7+ is not publish in apt,I fixed the problem with downgrade my rpi.
