### ISSUE TITLE
can't connect to 5ghz wifi

### ISSUE THREAD

**Issue by marc0601** [aircrack-ng/rtl8812au#142]
i can connect normally to 2.4ghz wifi but when i try to connect to 5ghz wifi, it keeps connecting, nothing else please help, 

in other drivers 5ghz wifi works well but aircrack doesn't work because interface name is wlx502b73d4075c not wlan0 and can't enable monitor mode please help me and thx :)

**Comment by kimocoder** [comment]
How do you enable monitor mode with this driver?

**Comment by tehhellhound** [comment]
The interface gets weird names with this chipset with any driver that actually works. This is the only one that doesn't lose massive packets when stressed with high speed UDP streams. I had this problem at first. Bring the interface down and back up. Forget the 5 gigahertz network if you're using a network manager. Connect to your 2.4 gigahertz network then bring the interface down and back up again. Now try your 5 gigahertz network. It works for me after that initial connection to the 2.4 gigahertz network.

**Comment by kimocoder** [comment]
Try using the v5.2.20 branch. Can't find any problems on 5ghz networks atm.
Open this issue if the problem persists, as I don't got any answers to my questions.

Thanks
