### ISSUE TITLE
low bitrate

### ISSUE THREAD

**Issue by magadan10** [aircrack-ng/rtl8812au#143]
Hello
I have have AWUS1900. With this driver device succesfully connected to laptop over USB with Super Speed (usb3), and when I conneted to the AP( 4x4:4 MIMO 80Mhz ) iwconfig show me the rate 450 Mbps. 
When I used the driver  from here https://github.com/zebulon2/rtl8814au, I got 1300 Mbps, but usb speed was High (this is usb2). Any advice?

**Comment by chiefdome** [comment]
having the same issue on fedora 28

**Comment by ahbrosha** [comment]
Same here. 1300Mbps works with: https://github.com/zebulon2/rtl8814au

**Comment by kimocoder** [comment]
Yes, it's on the TODO list on v5.3.4 branch.

**Comment by fariouche** [comment]
It should be ok now with v5.3.4. (works for some of us at least)

**Comment by francoism90** [comment]
@fariouche Just to be safe, is testing with `iwconfig` enough to validate?

**Comment by fariouche** [comment]
should be good. iwconfig is just not supported with some advanced functions (like fixed txpower)
