### ISSUE TITLE
unable to scan with wpa_supplicant git

### ISSUE THREAD

**Issue by ZeroChaos-** [aircrack-ng/rtl8812au#161]
This is probably a long term goal, but this driver doesn't scan (and hence doesn't work at all) with wpa_supplicant git.  Given wpa3 was recently ratified I've been expecting a release soon, so testing should start asap.

**Comment by kimocoder** [comment]
Try switching the "CONFIG_DISABLE_REGD_C" to "n" in Makefile. I'll take a dive into it in a week or so

**Comment by kimocoder** [comment]
Read https://wiki.archlinux.org/index.php/WPA_supplicant#nl80211_driver_not_supported_on_some_hardware

Under "nl80211 driver not supported on some hardware" there might be a solution, using "-d wext"

Haven't used wpa_supplicant for scanning, but will check it out. There is also an API for how to implement the support for it available, so lets see how this goes. wpa_supplicant is working with WPA3 implementation these days, so getting it to work should be a priority soon.

**Comment by ZeroChaos-** [comment]
as I've previously mentioned on this bug tracker, wext is just a compatibility layer which calls nl80211 at this time.  that said, I can certainly try it, but since the driver works with nl80211 in the stable wpa_supplicant, I think this should be fixed to work with nl80211 in the next release as well

**Comment by kcdtv** [comment]
It works with the new branch:  https://github.com/aircrack-ng/rtl8812au/pull/182
![seleccion_082](https://user-images.githubusercontent.com/7338484/44632531-e0f52080-a97c-11e8-880e-29d8354936a9.png)

**Comment by kimocoder** [comment]
That's just great. Seems like a MUCH better base then the others, see several improvements to it. Also supporting MESH.

**Comment by kcdtv** [comment]
I think that `iw scan` command was not working neither. With this branch it works just fine. :smiley_cat:

**Comment by ZeroChaos-** [comment]
5.3.4 cannot set channel with iw/netlink
```
Error setting channel: command failed: Device or resource busy (-16)
```

5.2.20 and 5.1.5 both could

I know you guys probably don't had me personally, and maybe realtek doesn't either... but it's hard to see that through the tears that this driver causes

**Comment by kimocoder** [comment]
Adding it to the TODO list! Thanks for your findings

**Comment by kimocoder** [comment]
@ZeroChaos- I think i found the problem... I close this and we move over to #396 
I wrote my newly discovered findings there.
