### ISSUE TITLE
Lost driver after "apt dist-upgrade"

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/rtl8812au#176]
After executing the "apt dist-upgrade" command and computer reboot, the drivers disappeared, the network does not catch, when entering the command "iwconfig" there are only eth0 and lo. But the computer sees the device itself. And if you install the driver again, nothing happens, PLEASE HELP!

P.S Sorry for my english

**Comment by kimocoder** [comment]
I bet you upgraded the Linux kernel.

git clone https://github.com/aircrack-ng/rrl8812au - b v5.2.20
cd rtl8812au
make -j4 && make install

**Comment by ghost** [comment]
@kimocoder That working with dkms?

**Comment by kimocoder** [comment]
For DKMS, run "dkms-install.sh"

**Comment by ghost** [comment]
U are the BEST! Thank you
