### ISSUE TITLE
not connecting on 2.4Ghz and unsupported channel on 5Ghz

### ISSUE THREAD

**Issue by limones1319** [aircrack-ng/rtl8812au#184]
Hi,

I came across two problems. When using 2.4 Ghz it's trying 4 times to do the handshake and then it gives up. When using 5Ghz the SSID does not even show up in the list and it says:

IEEE 802.11 Configured channel (36) not found from the channel list of current mode (2) IEEE 802.11a

Any idea how can I solve this problem?

Thanks,
Gabriel

**Comment by kimocoder** [comment]
Need more information here.. which branch, which adapter/chipset?

**Comment by limones1319** [comment]
v.5.2.20
TPLINK Archer T4UH

Bus 006 Device 002: ID 2357:010e

**Comment by limones1319** [comment]
[ 6822.450061] usb 5-1: new high-speed USB device number 2 using xhci_hcd
[ 6822.578874] usb 5-1: New USB device found, idVendor=2357, idProduct=010e, bcdDevice= 0.00
[ 6822.578885] usb 5-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 6822.578891] usb 5-1: Product: 802.11n NIC
[ 6822.578896] usb 5-1: Manufacturer: Realtek
[ 6822.578901] usb 5-1: SerialNumber: 123456
[ 6830.205746] usb 6-1: new SuperSpeed Gen 1 USB device number 3 using xhci_hcd
[ 6830.208762] usb 5-1: USB disconnect, device number 2
[ 6830.220235] usb 6-1: Int endpoint with wBytesPerInterval of 512 in config 1 interface 0 altsetting 0 ep 133: setting to 64
[ 6830.222218] usb 6-1: New USB device found, idVendor=2357, idProduct=010e, bcdDevice= 0.00
[ 6830.222227] usb 6-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 6830.222232] usb 6-1: Product: 802.11n NIC
[ 6830.222237] usb 6-1: Manufacturer: Realtek
[ 6830.222242] usb 6-1: SerialNumber: 123456

**Comment by kimocoder** [comment]
That last output looks good. That chipset is running om 8812au chipset.
Will try re-producing the problem.

**Comment by limones1319** [comment]
I forgot to say that I am using hostapd with CentOS Linux release 7.5.1804 (Core) and the .conf that you mentioned on issue #130

**Comment by kimocoder** [comment]
Aaah ok. I'm not using hostapd myself, I know there is a problem with finding a working configuration for it. Haven't even tried that conf myself. Try googling after a working configuration for the rtl8812au chipset, and I'll propably will look at it soon

**Comment by fariouche** [comment]
if possible, can you check with v5.3.4?

**Comment by limones1319** [comment]
I tried v5.3.4 and it's working in 5Ghz at 54 Mbps on channel 36, but it does not work on any other channel. It can not set the channel.

Besides this I am trying to make it work with 80 Mhz channel width like this:

http://blog.fraggod.net/2017/04/27/wifi-hostapd-configuration-for-80211ac-networks.html

But it doesn't work.

**Comment by fariouche** [comment]
I do remember having tested that configuration, and 80MHz was not possible in my case because of too many wifi around me.

Channel 36 is pretty crowded, and the driver may not be very good at selecting higher rate if there is noise.
I haven't test this dongle, but with 3 other models, I was able to have a fast speed with my phone.

I do not remember exactly the setup, but you may need to specify the vht_capab variable
vht_capab=[MAX-MPDU-11454][RXLDPC][SHORT-GI-80][TX-STBC-2BY1][RX-STBC-123]
(to adapt depending on the reported capabilities of your dongle using iw)

**Comment by kimocoder** [comment]
@limones1319 

There are many newer releases available. Move over to v5.6.4.2 and many issues should be resolved, if not.. please re-open this issue or a new one if you stumble upon something. Thanks!
