### ISSUE TITLE
Compiling on RPI 3B Rasbian 4.14.69-v7+

### ISSUE THREAD

**Issue by 1nval1d** [aircrack-ng/rtl8812au#202]
Hey guys,

I just tried to compile v5.1.5 on a Raspberry Pi 3 Model B running Rasbian and Kernel version 4.14.69-v7+ and wanted to let you know, that I got several issues that were hard to reproduce. I disabled multi threaded compiling and that worked out. gcc version is 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1).

So if someone else has this issue, edit the Makefile and search for "modules:"
In the line below remove the "-j" option and everything that follows until "ARCH=".

Thanks for the great project, it built without any issues on Kali Linux btw, same source.

PS: DKMS didnt work out, got Error code 2.

**Comment by kimocoder** [comment]
Disabled multi-threading. Closing. Thanks!
