### ISSUE TITLE
What version of the driver do you recommend for the EW-7833UAC

### ISSUE THREAD

**Issue by jagarzone6** [aircrack-ng/rtl8812au#203]
Currently I am using branch 5.1.5 in Ubuntu 18.04.1 LTS - Kernel 4.15.0-34-generic,  with the EW-7833UAC from edimax, 
It works very fine when I am close the modem, but have some issues finding networks and reconnecting. 
Is EW-7833UAC supported in recent branches ?, Are there some improvements related to the problems I had or should I stay in 5.1.5 ?

I know this is not an issue, but do not know where else to ask.

**Comment by kimocoder** [comment]
For now, use the "v5.2.20" (which actually is v5.2.20.2), less bugs, more fixes (added by Realtek too) until the v5.3.4 goes off "W.I.P" (see issue report)

**Comment by kimocoder** [comment]
I gave you the answer above. The v5.2.20 is currently suggested until v5.3.4 is ready.
