### ISSUE TITLE
v5.3.4 build not working on Ubuntu 18.04 kernel 4.15.0-36

### ISSUE THREAD

**Issue by etem** [aircrack-ng/rtl8812au#212]
When built with both RTL8812A=y, RTL8821A=y and RTL8814A=y options the driver is loaded but I can't see any networks. Restarting Network manager makes no difference: 
![with 8814-1](https://user-images.githubusercontent.com/8333647/46579383-0879e700-ca19-11e8-9157-8e12801a3ae1.png)

Without the RTL8814A switch I'm getting this warning message on compilation:
> WARNING: "mpt_ProSetPMacTx" [/var/lib/dkms/rtl8812au/5.3.4/build/8812au.ko] undefined!
[make.log](https://github.com/aircrack-ng/rtl8812au/files/2453676/make.log)

Dmesg errors after loading the module(compiled with RTL8814A=n): 
![manual installation](https://user-images.githubusercontent.com/8333647/46579421-095f4880-ca1a-11e8-8c18-c0ae7d247ba3.png)

I'm using a Comfast CF-915AC adapter with RTL8811AU chipset.

**Comment by kimocoder** [comment]
The error should now be fixed. Try again

**Comment by fariouche** [comment]
I will try the 8811 as soon as I have some free time, I thin I have the chipset at hand

**Comment by fariouche** [comment]
ok, got it working by removing 8814 and 8812 support. (in fact it the 8812 that interfere with the 8821 code)
Most likely a conflicting flag somewhere. This may take time to find the exact flag, but hopefully not hard to fix

**Comment by fariouche** [comment]
found it, again, a bug in the original realtek driver code.
It is a easy fix. (wrong firmware loaded - lol -)
I will cleanup tomorrow and push the fix

**Comment by etem** [comment]
@fariouche what would be the correct way for compiling the driver for the 8811 chip? Should I only turn on the CONFIG_RTL8821A = y switch in the Makefile?

**Comment by fariouche** [comment]
it should now work out of the box. It is fixed and pushed a few minutes ago in branch 5.3.4

**Comment by kimocoder** [comment]
This issue has been resolved.

Use "git pull" to update, compile and build again (make && make install)
Then reload it with "modprobe -r 88Xxau" and "modprobe 88XXau" or simpelt by rebooting.

Closing

**Comment by etem** [comment]
I will have the chance to test this after a week. Thank you very much!
