### ISSUE TITLE
Linux headers out of date?

### ISSUE THREAD

**Issue by bjornbracko** [aircrack-ng/rtl8812au#218]
When i try to install with dkms-install.sh i get the error 

> Your kernel headers for kernel 4.17.0-kali1-amd64 cannot be found at
/lib/modules/4.17.0-kali1-amd64/build or /lib/modules/4.17.0-kali1-amd64/source.

but on kali rolling, current headers are 4.18.0

**Comment by francoism90** [comment]
You don't have the right `linux-headers` package: https://stackoverflow.com/questions/50759974/unable-to-locate-package-linux-headers-4-15-0-kali2-amd64

**Comment by kimocoder** [comment]
Install the correct linux-headers package. Not a driver issue. Closing.
