### ISSUE TITLE
5.3.4 issues with promisc/rfmon mode

### ISSUE THREAD

**Issue by rofl0r** [aircrack-ng/rtl8812au#238]
https://github.com/t6x/reaver-wps-fork-t6x/issues/265#issuecomment-441272085

**Comment by kimocoder** [comment]
Continue the conversation over there. Leaving this open

**Comment by kimocoder** [comment]
Thanks for adding the fix on reaver @rofl0r shoutout to @kcdtv as well! Love :1st_place_medal:
