### ISSUE TITLE
Issue with airodump-ng 

### ISSUE THREAD

**Issue by Bluewild93** [aircrack-ng/rtl8812au#24]
I installed your driver 4.3.21, it works perfect for the first time when i put it in the monitor mode then sent DeAuth to my target devices. My target devices was disconnect from my wifi. But i couldn't get any handshakes. The second time, i couldn't get anything from the airodump-ng 
![img_0088](https://user-images.githubusercontent.com/14236569/31361435-a39d8da6-ad53-11e7-9c52-5fd191d106cd.JPG)

**Comment by kimocoder** [comment]
just bring it down with:
ifconfig <adapter> down

then up again with:
ifconfig <adapter> up

in monitor mode, then it should work again..

**Comment by Bluewild93** [comment]
do i need the newest version that you have now or just use it 4.3.21?

**Comment by kimocoder** [comment]
v5.2.9 is for 8812au only, not the 8814au but it's not complete. But you could try the v5.1.5 :)

**Comment by Bluewild93** [comment]
Thank you so much for your fast answer. 
I just wonder what course or program should people take to write a driver or program that you are doing now. Absolutely wonderful.

**Comment by kimocoder** [comment]
credits still goes to "astsam", this is a fork from his repo with some extras added (like kernel support)

it's written in C

**Comment by kimocoder** [comment]
The scanning issue has been resolved in latest "EFUSE fix" commits in v5.1.5 branch.
It has been tested and it seems to work fine noe. Closing.
