### ISSUE TITLE
Please help for monitor mode name

### ISSUE THREAD

**Issue by Phoenix1112** [aircrack-ng/rtl8812au#245]
i am using tenda u12 ac1300 wifi adapter.  İ did install RTL8812AU driver and it is working now.

but  have any problem... i am putting wifi adapter into monitor mode...

but wlan1mon does not write after switching to monitor mode....wlan1 does not change when I switch to monitor mode...but monitor mode is working....I wanted to do an injection attack using the airgeddon program, but it doesn't happen.. i can deauth attack. i can catch handshake... but when the evil twin attack starts, the terminals open but not attack..deauth attack terminal says "mon: failed" ...I think I got this error because the monitor mode name is not wlan1mon...my monitor mode name "wlan1"

How do I change the name to wlan1mon when I put wifi adapter in monitor mode ??

![1](https://user-images.githubusercontent.com/42475284/50024171-957d8580-fff2-11e8-826b-69241ab66aea.png)

![2](https://user-images.githubusercontent.com/42475284/50024178-9d3d2a00-fff2-11e8-864f-049e013e52fc.png)

![3](https://user-images.githubusercontent.com/42475284/50024190-a5956500-fff2-11e8-93d0-20ddd57fab1e.png)

**Comment by kimocoder** [comment]
You cannot. This driver doesn't support virtual interfaces. You should notice the airgeddon developers to add support for the drivers (drivers without virtual interface support). Closing

**Comment by evilginx** [comment]
İ dont understand .This is airgeddon error? Wlan1 monitor mod3 can work other evil twin attack?

**Comment by kimocoder** [comment]
Yes, they should add a function to check for devices inn monitor mode, instead of looking for "wlan0mon" or "wlan1mon" or how they do it.
