### ISSUE TITLE
Examining the connection details causes a disconnection

### ISSUE THREAD

**Issue by RainehDaze** [aircrack-ng/rtl8812au#247]
Looking at the connection in network manager (kde) or via the system monitor causes the connection to stop working, then disconnect entirely.

This is true for both the 5ghz and 2.6ghz bands, with separate SSIDs for each band.

**Comment by francoism90** [comment]
Any logging in `dmesg` and `journalctl -xe`? Sometimes this also happens to me, and the only workaround is to reboot.

**Comment by RainehDaze** [comment]
It doesn't seem like there's anything logged there--I just thought it was worth noting that regardless of any general instability with the 5ghz connection, it _specifically_ fails when opening anything that wants to measure or inspect the connection--sometimes immediately, sometimes after a few seconds.

**Comment by francoism90** [comment]
Would it be possible to test a different network backend? At the moment I'm using iwd and systemd-networkd, so far the connection seems to be stable.

**Comment by RainehDaze** [comment]
I tried, but with iwd I couldn't get it to connect to the network at all--possibly I could fix that by completely disabling network manager and then rebooting and trying to connect, but I'd probably just leave myself with no working connection at all.

**Comment by kimocoder** [comment]
And what branch (version) of the driver are you using?

**Comment by RainehDaze** [comment]
5.2.20; someone I was talking with to get my adaptor working reported the same issue with 5.3.4.

**Comment by kimocoder** [comment]
Ok. I'll check when I'm back home.

**Comment by kimocoder** [comment]
This issue should be resolved. Please use latest branch, if not please re-open
