### ISSUE TITLE
Kernel 4.20.0 errors well loading module

### ISSUE THREAD

**Issue by nater1983** [aircrack-ng/rtl8812au#252]
[   50.066816] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   50.074647] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   50.550899] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   50.550907] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   52.975888] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   57.730254] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   60.963892] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   60.967733] WARNING: CPU: 0 PID: 926 at /root/t/rtl8812au/core/rtw_mlme_ext.c:11848 rtw_mlmeext_disconnect+0xea/0x13e [88XXau]
[   60.967734] Modules linked in: ipv6 8021q garp mrp stp llc 88XXau(O) hid_generic cfg80211 rfkill usbhid hid ppdev gpio_ich evdev dcdbas uhci_hcd snd_hda_codec_analog snd_hda_codec_generic coretemp kvm irqbypass i915 video psmouse cec rc_core serio_raw drm_kms_helper i2c_i801 ehci_pci ehci_hcd drm snd_hda_intel snd_hda_codec i2c_algo_bit lpc_ich fb_sys_fops syscopyarea snd_hda_core sysfillrect sysimgblt tg3 snd_hwdep i2c_core snd_pcm snd_timer snd libphy soundcore hwmon intel_agp intel_gtt agpgart parport_pc parport button loop
[   60.967760] CPU: 0 PID: 926 Comm: NetworkManager Tainted: G           O      4.20.0 #1
[   60.967761] Hardware name: Dell Inc. OptiPlex 360                 /0T656F, BIOS A07 06/18/2012
[   60.967787] EIP: rtw_mlmeext_disconnect+0xea/0x13e [88XXau]
[   60.967788] Code: 00 e8 ad 80 ee dc c6 83 9a 05 00 00 00 c7 83 9c 05 00 00 00 00 00 00 8b 45 f4 65 33 05 14 00 00 00 75 56 8d 65 f8 5b 5e 5d c3 <0f> 0b e9 4d ff ff ff c6 45 f0 00 8d 4d f0 ba 59 00 00 00 89 d8 e8
[   60.967790] EAX: 00000800 EBX: f7ce4000 ECX: 00000000 EDX: f3f0c990
[   60.967791] ESI: f7ce4ade EDI: 00000001 EBP: f3f6b8d4 ESP: f3f6b8c0
[   60.967792] DS: 007b ES: 007b FS: 0000 GS: 00e0 SS: 0068 EFLAGS: 00210206
[   60.967793] CR0: 80050033 CR2: 096b714c CR3: 33f3f000 CR4: 000406d0
[   60.967794] Call Trace:
[   60.967822]  ? disconnect_hdl+0x4a/0xbe [88XXau]
[   60.967843]  ? rtw_disassoc_cmd+0x49/0x14e [88XXau]
[   60.967847]  ? qdisc_reset+0x1e/0xb0
[   60.967880]  ? netdev_close+0x54/0xc9 [88XXau]
[   60.967883]  ? __dev_close_many+0x8c/0x100
[   60.967885]  ? __dev_change_flags+0xa8/0x1d0
[   60.967886]  ? dev_change_flags+0x28/0x60
[   60.967889]  ? do_setlink+0x2ac/0x9d0
[   60.967901]  ? __snmp6_fill_stats64.constprop.70+0x80/0xf0 [ipv6]
[   60.967905]  ? __nla_parse+0x27/0x140
[   60.967907]  ? rtnl_newlink+0x730/0x860
[   60.967910]  ? __nla_reserve+0x31/0x40
[   60.967911]  ? nla_put+0x2a/0x40
[   60.967919]  ? inet6_fill_ifla6_attrs+0x3db/0x400 [ipv6]
[   60.967927]  ? inet6_fill_ifla6_attrs+0x400/0x400 [ipv6]
[   60.967935]  ? inet6_fill_link_af+0x17/0x30 [ipv6]
[   60.967936]  ? rtnl_fill_ifinfo+0xb86/0xd50
[   60.967939]  ? netlink_attachskb+0x1d9/0x200
[   60.967940]  ? __netlink_lookup+0xb2/0x110
[   60.967942]  ? __netlink_sendskb+0x44/0x60
[   60.967944]  ? netlink_attachskb+0x1d9/0x200
[   60.967946]  ? __netlink_lookup+0xb2/0x110
[   60.967947]  ? __netlink_sendskb+0x44/0x60
[   60.967950]  ? cap_inode_getsecurity+0x200/0x200
[   60.967951]  ? security_capable+0x32/0x50
[   60.967953]  ? rtnl_link_unregister+0xe0/0xe0
[   60.967954]  ? rtnetlink_rcv_msg+0x1ef/0x310
[   60.967956]  ? proto_seq_start+0x30/0x30
[   60.967958]  ? rtnl_calcit.isra.33+0x100/0x100
[   60.967959]  ? netlink_rcv_skb+0x6e/0xf0
[   60.967961]  ? netlink_unicast+0x19c/0x250
[   60.967962]  ? netlink_sendmsg+0x22e/0x390
[   60.967964]  ? netlink_unicast+0x250/0x250
[   60.967966]  ? sock_sendmsg+0x32/0x40
[   60.967968]  ? ___sys_sendmsg+0x23d/0x260
[   60.967970]  ? ___sys_recvmsg+0x109/0x150
[   60.967972]  ? __alloc_pages_nodemask+0xe0/0xd40
[   60.967974]  ? __sys_sendmsg+0x3e/0x80
[   60.967976]  ? sys_socketcall+0x14a/0x2b0
[   60.967979]  ? do_int80_syscall_32+0x4b/0xf0
[   60.967981]  ? entry_INT80_32+0xc9/0xc9
[   60.967983] ---[ end trace 525a29623935cbad ]---
[   61.039781] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   61.210780] WARNING: CPU: 0 PID: 926 at /root/t/rtl8812au/core/rtw_mlme_ext.c:11848 rtw_mlmeext_disconnect+0xea/0x13e [88XXau]
[   61.210782] Modules linked in: ipv6 8021q garp mrp stp llc 88XXau(O) hid_generic cfg80211 rfkill usbhid hid ppdev gpio_ich evdev dcdbas uhci_hcd snd_hda_codec_analog snd_hda_codec_generic coretemp kvm irqbypass i915 video psmouse cec rc_core serio_raw drm_kms_helper i2c_i801 ehci_pci ehci_hcd drm snd_hda_intel snd_hda_codec i2c_algo_bit lpc_ich fb_sys_fops syscopyarea snd_hda_core sysfillrect sysimgblt tg3 snd_hwdep i2c_core snd_pcm snd_timer snd libphy soundcore hwmon intel_agp intel_gtt agpgart parport_pc parport button loop
[   61.210808] CPU: 0 PID: 926 Comm: NetworkManager Tainted: G        W  O      4.20.0 #1
[   61.210809] Hardware name: Dell Inc. OptiPlex 360                 /0T656F, BIOS A07 06/18/2012
[   61.210834] EIP: rtw_mlmeext_disconnect+0xea/0x13e [88XXau]
[   61.210836] Code: 00 e8 ad 80 ee dc c6 83 9a 05 00 00 00 c7 83 9c 05 00 00 00 00 00 00 8b 45 f4 65 33 05 14 00 00 00 75 56 8d 65 f8 5b 5e 5d c3 <0f> 0b e9 4d ff ff ff c6 45 f0 00 8d 4d f0 ba 59 00 00 00 89 d8 e8
[   61.210837] EAX: 00000800 EBX: f7ce4000 ECX: 00000000 EDX: f3f0cd90
[   61.210838] ESI: f7ce4ade EDI: 00000001 EBP: f3f6b8d4 ESP: f3f6b8c0
[   61.210839] DS: 007b ES: 007b FS: 0000 GS: 00e0 SS: 0068 EFLAGS: 00210206
[   61.210840] CR0: 80050033 CR2: b7e1fd80 CR3: 33f3f000 CR4: 000406d0
[   61.210841] Call Trace:
[   61.210870]  ? disconnect_hdl+0x4a/0xbe [88XXau]
[   61.210890]  ? rtw_disassoc_cmd+0x49/0x14e [88XXau]
[   61.210894]  ? qdisc_reset+0x1e/0xb0
[   61.210927]  ? netdev_close+0x54/0xc9 [88XXau]
[   61.210930]  ? __dev_close_many+0x8c/0x100
[   61.210932]  ? __dev_change_flags+0xa8/0x1d0
[   61.210934]  ? dev_change_flags+0x28/0x60
[   61.210936]  ? do_setlink+0x2ac/0x9d0
[   61.210951]  ? __snmp6_fill_stats64.constprop.70+0x80/0xf0 [ipv6]
[   61.210955]  ? __nla_parse+0x27/0x140
[   61.210956]  ? rtnl_newlink+0x730/0x860
[   61.210960]  ? ext4_mark_iloc_dirty+0x5ed/0x830
[   61.210962]  ? ext4_reserve_inode_write+0x7c/0xb0
[   61.210963]  ? ext4_mark_inode_dirty+0x74/0x180
[   61.210966]  ? ext4_split_extent_at+0x232/0x420
[   61.210967]  ? ext4_ext_try_to_merge+0x44/0x140
[   61.210969]  ? ext4_split_extent_at+0x232/0x420
[   61.210971]  ? ext4_find_extent+0x50/0x2b0
[   61.210973]  ? ep_scan_ready_list.constprop.21+0x1a7/0x1b0
[   61.210975]  ? ep_item_poll.isra.18+0xb0/0xb0
[   61.210976]  ? ep_eventpoll_poll+0x50/0x70
[   61.210978]  ? do_sys_poll+0x30c/0x5a0
[   61.210982]  ? update_curr+0xbf/0x1b0
[   61.210983]  ? ext4_mark_iloc_dirty+0x5ae/0x830
[   61.210986]  ? cap_inode_getsecurity+0x200/0x200
[   61.210988]  ? security_capable+0x32/0x50
[   61.210989]  ? rtnl_link_unregister+0xe0/0xe0
[   61.210991]  ? rtnetlink_rcv_msg+0x1ef/0x310
[   61.210993]  ? yield_to_task_fair+0x60/0x60
[   61.210994]  ? rtnl_calcit.isra.33+0x100/0x100
[   61.210996]  ? netlink_rcv_skb+0x6e/0xf0
[   61.210998]  ? netlink_unicast+0x19c/0x250
[   61.210999]  ? netlink_sendmsg+0x22e/0x390
[   61.211001]  ? netlink_unicast+0x250/0x250
[   61.211004]  ? sock_sendmsg+0x32/0x40
[   61.211005]  ? ___sys_sendmsg+0x23d/0x260
[   61.211007]  ? check_preempt_wakeup+0x157/0x200
[   61.211009]  ? check_preempt_curr+0x72/0xa0
[   61.211010]  ? wake_up_q+0x3f/0x70
[   61.211013]  ? futex_wake+0xeb/0x120
[   61.211014]  ? do_futex+0x231/0x8d0
[   61.211016]  ? __sys_sendmsg+0x3e/0x80
[   61.211018]  ? __switch_to_asm+0x26/0x50
[   61.211020]  ? sys_socketcall+0x14a/0x2b0
[   61.211021]  ? __schedule+0x1ac/0x740
[   61.211023]  ? do_int80_syscall_32+0x4b/0xf0
[   61.211025]  ? entry_INT80_32+0xc9/0xc9
[   61.211026] ---[ end trace 525a29623935cbae ]---

**Comment by nater1983** [comment]
Version: v5.2.20.2_28373.20180619

Sorry almost forgot the driver version that I am testing out.

**Comment by francoism90** [comment]
Does it load the module and showing an interface? I'm also getting these kind of errors sometimes.

**Comment by nater1983** [comment]
Yes the driver is useable my hardware is found and it is useable.

**Comment by francoism90** [comment]
Try to load the driver without any (network) backends and on a fresh boot, this usually fixing the error on my system, although I simple ignore it.

**Comment by nater1983** [comment]
That works but i need the network backend just the way it is

**Comment by francoism90** [comment]
What backend are you using? It should work OK, don't know exactly what is causing the error, but like said before I just ignore it.

**Comment by nater1983** [comment]
nmcli is the first network backend that I am using at start up to auto
connect to my wireless network and then it switch's to NetworkManager
in Kde

**Comment by francoism90** [comment]
Hmm, could you try not to use NetworkManager and see what happens? At the moment I'm only using iwd, maybe the fast switching is causing this issue, but you better ask to the devs.

**Comment by nater1983** [comment]
I agree the fast switching would be the problem, on my other machinces they
all fastswitch from nmcli over to NetworkManager in Kde.
