### ISSUE TITLE
v5.2.20 - Problem with 80 Mhz bandwidth

### ISSUE THREAD

**Issue by francoism90** [aircrack-ng/rtl8812au#253]
Thanks for updating this module, I did some testing. :)

This is being reported on the v5.2.20 driver:
```
$ iwconfig                                                                                      
wlp0s20f0u4  IEEE 802.11  ESSID:".."  
          Mode:Managed  Frequency:5.24 GHz  Access Point: ..   
          Bit Rate=450 Mb/s   Tx-Power=30 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=67/70  Signal level=-43 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

lo        no wireless extensions.
```
The v5.3.4 branch shows the full 1300 Mb/s bitrate on my ASUS USB-AC68.

This seem to differ:
```
TX STBC => only showing on v5.2.20 - think this is a good thing?
RX STBC 1-stream => RX STBC 3-streams on v5.3.4
HT Max RX data rate: 404 Mbps => HT Max RX data rate: 450 Mbps on v5.3.4
SU Beamformer => only showing on v5.2.20 - think this is a good thing?
```
Maybe this is an issue with the STBC streams? Shouldn't they show 3, as this device should have more then one?

Thanks again for your hard work!

**Comment by aircrack-ng** [comment]
Are you sure the speed is really that much? What I mean is that what iwconfig reports is just information, it may not always be accurate (look at txpower, there is no way it's 30dbm). Do an iperf to confirm the speed.

**Comment by francoism90** [comment]
@aircrack-ng iperfs results:
```
------------------------------------------------------------
Client connecting to server, TCP port 5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  3] local <ip> port 34118 connected with <ip> port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.1 sec  99.4 MBytes  82.4 Mbits/sec
```

```
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size: 85.3 KByte (default)
------------------------------------------------------------
[  4] local <ip> port 5001 connected with <ip> port 34118
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-10.5 sec  99.4 MBytes  79.5 Mbits/sec
```

Latest router log:

```
Device | IP Address | Rx/Tx & RSSI | Connected | Flags
-- | -- | -- | -- | --
Chromecast | 176 / 293 Mbps | -65 dBm | 18:05:37 | AU
Galaxy-S9 | 780 / 650 Mbps | -57 dBm | 5:59:25 | AU
Desktop (rtl8812) | 270 / 81 Mbps | -46 dBm | 2:25:01
```
As you can see the desktop speed dropped a lot when using branch `v5.2.20`, using `v5.3.4` it will perform like the Galaxy S9 is doing.

**Comment by ValZapod** [comment]
@kimocoder Any comments?

**Comment by francoism90** [comment]
@kimocoder @ValZapod I don't have this device anymore. Will leave it open.

**Comment by ValZapod** [comment]
@kimocoder This IS a problem for me on latest kali driver 5.2.20.2~20181106-0kali1. So... Maybe it was already solved but maybe not.

**Comment by kimocoder** [comment]
I've started looking just now :+1:

**Comment by ValZapod** [comment]
@kimocoder I suppose this 
> TX STBC => only showing on v5.2.20 - think this is a good thing?

is because of this https://github.com/aircrack-ng/rtl8812au/commit/dbd216d9a06c99703e8fec259c68fdceb901415b?

And BTW what is this
https://github.com/aircrack-ng/rtl8812au/commit/86079bb084e3576adb1a8f159a7437cf521a9e1f?
What are these streams?

**Comment by kimocoder** [comment]
1. You may try fiddling with this setting
    (just remember "modprobe -r 88XXau && modprobe 88XXau" after build/install)

2. The spatial streams is hardcoded in the driver, and on the 8814 HAL it was only using 1 stream, fariouche made all 4 streams working in the 8814.

**Comment by ValZapod** [comment]
@kimocoder But 8814 can use only 3 spatial streams even if there're 4 TX and 4 RX antennas!

**Comment by ValZapod** [comment]
@kimocoder I have another question. RTL8814 is 802.11ac 4x4, 3 spatial streams MIMO, so 1300 Mbit/s Max (3SS, 80 MHz, 400 ns GI, MCS 9) (https://www.realtek.com/en/products/communications-network-ics/item/rtl8814au, Realtek redesigned their servers, yeah).
Again, for 802.11n in 2.4 MHz it's capable of 600 Mbit/s (so 31 MCS index: 400 ns GI, 40 MHz channel, 4
SS). Maybe it is what changed in 86079bb.
But what are the capabilities for 802.11n (n!) in 5 MHz??? Look at this issue: https://github.com/aircrack-ng/rtl8812au/issues/225

**Comment by francoism90** [comment]
@ValZapod I suggest to clone this repo, revert these commits and see if it makes a differences.

I'm also closing this issue since I don't have the device anymore.

**Comment by ValZapod** [comment]
@francoism90 It won't make a difference: these commits are for TX STBC (MIMO technology on top of working Spacial Streams) and Spacial Streams (but the issue is with bandwidth not spatial streams) so please reopen.
