### ISSUE TITLE
Kali 2019.1 - Alfa AWUS036ACH - Injection not working

### ISSUE THREAD

**Issue by mfoolb** [aircrack-ng/rtl8812au#257]
Hello,
running Kali 2019.1 (no VM) on Acer Laptop with Windows10.
I've tested the adapter with both driver (last version from kali repo and Github).

The signal range is really bad, I can only make injection work standing by my own AP.

Other problem is the USB 3.0 connection. Signal is worst if I plug the adapter to a 3.0 port (lsusb -v MaxPower 200ma), a bit better but not usable using the 2.0 port (MaxPower shown at 500ma).

I'm happy to help if and how I can.

**Comment by kimocoder** [comment]
@mfoolb We've did some work on the injection on both v5.2.20(.2) and v5.3.4 branch.
The range we're aware about, but it isn't the USB 3.0 connection, "usbutils" was simply outdated so it shows 850++ now. There is another issue threads about them, continue there if so :+1:
