### ISSUE TITLE
ALFA AWUS036AC Stuck on: : Starting Captive Portal access point service

### ISSUE THREAD

**Issue by MiladShojaei** [aircrack-ng/rtl8812au#260]
hi - i'm using last kernel and upgrade of Kali . but i can't use Fluxion or airgeddon or anything else in wifi-cracking

is there any good driver for this modem , i think the problem is injection mode in alfa

**Comment by MiladShojaei** [comment]
Thx but I upgrade and update Kali to the last version but still no

Should i upgrade airmon?is this possible at all?

**Comment by ValZapod** [comment]
Does this in terminal apt-get update; apt-get -y  dist-upgrade; apt-get -y a
utoremove; apt-get clean

**Comment by MiladShojaei** [comment]
Thx. Will do

**Comment by kimocoder** [comment]
Closing this issue
