### ISSUE TITLE
List of compatibility chips.

### ISSUE THREAD

**Issue by artchizhov** [aircrack-ng/rtl8812au#268]
It is not issue, but i do not find full information about compatibility other chips.

I right, that this chips is WORK:
8811AU
8812AU
8814AU

8821AU

and this is NOT work:
8812BU

etc...

Right?

**Comment by kcdtv** [comment]
You are right
The supported chip follow this pattern **88XXAU**
That why the module created is called "88XXau" and it is a unique module that supports all the chipsets from this "family"

**Comment by kimocoder** [comment]
You are correct. Those 4 chipsets, we could add more but.. it's a big hazzle to do it :+1:
