### ISSUE TITLE
ArchLinux package available

### ISSUE THREAD

**Issue by noraj** [aircrack-ng/rtl8812au#269]
Hi,

I packaged the driver in v5.2.20 for ArchLinux: https://aur.archlinux.org/packages/rtl8812au-aircrack-ng-dkms-git/ and successfully built and use it for kernel 4.20.3-1-MANJARO.

I saw you added a kali supported badge, maybe you want one for archlinux/blackarch? (I made a PR #270)

This is just to let you know, giving feedback. By the way thanks to maintain this driver.

**Comment by ghost** [comment]
There's this package called [rtl88xxau-aircrack-dkms-git](https://aur.archlinux.org/packages/rtl88xxau-aircrack-dkms-git/) now, I think it replaces the previous package nicely. It also reflects that the drive is unified. Your help is better needed there.

I don't think the package [rtl8812au-aircrack-ng-dkms-git](https://aur.archlinux.org/packages/rtl8812au-aircrack-ng-dkms-git/) should exist.

**Comment by noraj** [comment]
@JpegXguy Thanks. I didn't found it because the description and tags don't contains `rtl8812au`.

![image](https://user-images.githubusercontent.com/16578570/52539426-3e8bf680-2d7e-11e9-83cc-ce66e8d5fadb.png)

**Comment by ghost** [comment]
I see. We'd thought of 8812au being there in the search but not with the rtl, I'll make a comment

**Comment by noraj** [comment]
@JpegXguy instead of a package deletion for my package why not a merge (see https://wiki.archlinux.org/index.php/Arch_User_Repository#Other_requests) ?

**Comment by ghost** [comment]
It didn't have any comments or votes and I didn't think of it. Merge is better in general, so you're right

**Comment by kimocoder** [comment]
Awesome. Thanks for the heads up :v:
