### ISSUE TITLE
tshark startup fails with v5.3.4

### ISSUE THREAD

**Issue by Chadster766** [aircrack-ng/rtl8812au#283]
OS: Debian Stretch
Module: 88XXau version:        v5.3.4_28226.20180614_COEX20171103-6c6d

tshark (Wireshark) fails to start with the below error:
```
tshark: The capture session could not be initiated on interface 'wlxc8d719be5f91' (wlxc8d719be5f91: SIOCGIWPRIV: Argument list too long).
```

Related Issue: https://github.com/aircrack-ng/rtl8812au/issues/277

**Comment by Chadster766** [comment]
Testing shows that tag v1.0-DEV **_doesn't_** have this issue 

tshark is able to put the interface into promiscuous mode in v1.0-DEV with the below journalctl output:
```
Feb 16 15:15:11 McDebian3 kernel: device wlxc8d719be5f91 entered promiscuous mode
Feb 16 15:15:14 McDebian3 kernel: device wlxc8d719be5f91 left promiscuous mode
```

**Comment by Chadster766** [comment]
I've narrowed it down to iwconfig not being able to set the wireless interface mode with this driver version.

**Comment by kimocoder** [comment]
iwconfig? iwconfig is deprecated anyway. use only "iw"

**Comment by Chadster766** [comment]
True, I will close this issue.
