### ISSUE TITLE
Can't install v5.2.2 on odroid XU4 kernel 4.14.5-92

### ISSUE THREAD

**Issue by jenesui** [aircrack-ng/rtl8812au#289]
I am in a fresh install of XU4 Ubuntu 16.04.

After clone v5.2.2, change the makefile to arm, I get:

CC [M]  /home/odroid/rtl8812au/core/rtw_cmd.o
In file included from ./include/linux/netfilter.h:8:0,
                 from ./include/linux/netfilter/nf_conntrack_tuple_common.h:6,
                 from ./include/linux/netfilter/nf_conntrack_dccp.h:29,
                 from ./include/net/netns/conntrack.h:11,
                 from ./include/net/net_namespace.h:27,
                 from ./include/linux/netdevice.h:42,
                 from /home/odroid/rtl8812au/include/osdep_service_linux.h:30,
                 from /home/odroid/rtl8812au/include/osdep_service.h:47,
                 from /home/odroid/rtl8812au/include/drv_types.h:27,
                 from /home/odroid/rtl8812au/core/rtw_cmd.c:17:
./include/linux/if.h:28:54: fatal error: sys/socket.h: No such file or directory
compilation terminated.

What can I do?

**Comment by kimocoder** [comment]
@jenesui v5.2.2 doesn't exist.. so.. I think your in the wrong repo? If not, open the issue up again and please provide correct and as much information as possible
