### ISSUE TITLE
AWUS036ACH Very poorly working on MacBook Pro

### ISSUE THREAD

**Issue by 4val0v** [aircrack-ng/rtl8812au#290]
Hello, there is _AWUS036ACH_ but it works differently on different PCs.
**OS:** Kali Linux 2019.1
**Driver** _v5.2.20.2_ installed from repository: `apt install realtek-rtl88xxau-dkms`

**MacBook:** - _My phone is a lot more wi-fi points sees ;)_
![MacBook PRO 2015](https://user-images.githubusercontent.com/11297476/53826714-fda08f80-3f81-11e9-9522-ed36ac614dec.png)
![um meter - macbook pro](https://user-images.githubusercontent.com/11297476/53828700-1495b080-3f87-11e9-9ee3-1616461115a8.png)

**Samsung NP270:** - _More wi-fi access points_ **_(Sees +9 more networks)_**
![screenshot from 2019-03-05 18-38-37 1](https://user-images.githubusercontent.com/11297476/53829172-36dbfe00-3f88-11e9-98a4-2bb584c29fa3.png)
![um metersamsung](https://user-images.githubusercontent.com/11297476/53829399-b8cc2700-3f88-11e9-8c91-639676bb9ab9.png)

How do I understand the problem because of the power supplied by the USB port ?

**Comment by 4val0v** [comment]
In the client mode does not work long _(after measuring the speed of the Internet, loses connection with the wifi point)_, see video.
The adapter only sees points near :(
https://youtu.be/cJScuHW-KSw

Log data from UM34C - [UM34C.xls.zip](https://github.com/aircrack-ng/rtl8812au/files/2936737/UM34C.xls.zip)

LinSSID sees more wi-fi points, but also far from ideal:
![2019-03-06 13-33-32](https://user-images.githubusercontent.com/11297476/53892932-e327ee00-4035-11e9-9140-0f1c3235a161.png)

_Checked on MacBook Pro, if needed I can check on another device_

**Comment by kimocoder** [comment]
This issue should be resolved on our newest branch v5.6.4.2, if not feel free to re-open this issue again. Thanks!
