### ISSUE TITLE
v5.3.4 - can't compile with debug mode enabled

### ISSUE THREAD

**Issue by kapitainsky** [aircrack-ng/rtl8812au#291]
Raspberry Pi: Linux DBRPi01 4.19.25-v7+ #1205 SMP Mon Feb 25 18:19:20 GMT 2019 armv7l GNU/Linux

When trying to compile v5.3.4 with debug mode enabled in Makefile:

`CONFIG_RTW_DEBUG = y
CONFIG_RTW_LOG_LEVEL = 4`

it fails with following error:

`  CC [M]  /media/db_tc_1/Varia/Sources/rtl8812au/os_dep/linux/xmit_linux.o
In file included from /media/db_tc_1/Varia/Sources/rtl8812au/include/drv_types.h:60:0,
                 from /media/db_tc_1/Varia/Sources/rtl8812au/os_dep/linux/usb_intf.c:17:
/media/db_tc_1/Varia/Sources/rtl8812au/os_dep/linux/usb_intf.c: In function ‘rtw_resume_process’:
/media/db_tc_1/Varia/Sources/rtl8812au/os_dep/linux/usb_intf.c:993:36: error: ‘_func__’ undeclared (first use in this function)
   RTW_INFO("%s bInSuspend = %d\n", _func__, pwrpriv->bInSuspend);
                                    ^
/media/db_tc_1/Varia/Sources/rtl8812au/include/rtw_debug.h:139:34: note: in definition of macro ‘RTW_INFO’
    _dbgdump(DRIVER_PREFIX fmt, ##arg);\
                                  ^~~
/media/db_tc_1/Varia/Sources/rtl8812au/os_dep/linux/usb_intf.c:993:36: note: each undeclared identifier is reported only once for each function it appears in
   RTW_INFO("%s bInSuspend = %d\n", _func__, pwrpriv->bInSuspend);
                                    ^
/media/db_tc_1/Varia/Sources/rtl8812au/include/rtw_debug.h:139:34: note: in definition of macro ‘RTW_INFO’
    _dbgdump(DRIVER_PREFIX fmt, ##arg);\
                                  ^~~
scripts/Makefile.build:303: recipe for target '/media/db_tc_1/Varia/Sources/rtl8812au/os_dep/linux/usb_intf.o' failed`

when I revert CONFIG_RTW_DEBUG to n it compiles without any issues.

**Comment by kimocoder** [comment]
I fixed it now, sorry for the delay, been busy with life.
The function "__func__" got an error there you see.. a typo in

RTW_INFO("%s bInSuspend = %d\n", **_func__**, pwrpriv->bInSuspend);

Fix has been pushed, thanks for the report, sir! :1st_place_medal:
