### ISSUE TITLE
ALFA AWUS036AC: Association request to the driver failed (raspian stretch)

### ISSUE THREAD

**Issue by 0unknwn** [aircrack-ng/rtl8812au#293]
I'm using a RasPi 3 B + (latest and up to date raspbian stretch) with `systemd-networkd` and` wpa_supplicant`. When I restart the wpa_supplicant@wlan1.service I get a ` Association request to the driver failed` message. I don't have this issue with other wifi dongles. What could be the reason?

This is hat my service unit looks like:
```

[Unit]
Description=WPA supplicant daemon (interface-specific version)
Requires=sys-subsystem-net-devices-%i.device
After=sys-subsystem-net-devices-%i.device
Before=network.target
Wants=network.target

# NetworkManager users will probably want the dbus version instead.

[Service]
Type=simple
ExecStart=/sbin/wpa_supplicant -c/etc/wpa_supplicant/wpa_supplicant-%I.conf -Dnl80211,wext -i%I

[Install]
Alias=multi-user.target.wants/wpa_supplicant@%i.service

```

**Comment by chryzsh** [comment]
I installed from branch v5.4.3 and that solved this issue. However, wpa doesn't work in this version (either).

**Comment by 0unknwn** [comment]
The error is gone with v5.4.3 for me as well. And everything works fine!

**Comment by kimocoder** [comment]
We move over to the v5.3.4 in a while, some issues with reaver has been solved.
Please just be patient and I'll start on it.

**Comment by kimocoder** [comment]
Now the v5.3.4 branch has got several fixes added, including some hostapd fixes from @j-forestial
Also, there was a auth_seq and other minors that has been fixed.

It should be working better now, as we move over to v5.3.4. If not, open a new report!
Thanks! :+1:
