### ISSUE TITLE
rtl8812au_xmit.c : Compiler warns that conditional will always be false

### ISSUE THREAD

**Issue by rickhg12hs** [aircrack-ng/rtl8812au#308]
Current code that causes warning:
https://github.com/aircrack-ng/rtl8812au/blob/1ae2f322fcb597c298a81f93877af277984835e2/hal/rtl8812a/usb/rtl8812au_xmit.c#L445

Maybe this should be:
```C
while ((rtw_read32(adapter, REG_PKTBUF_DBG_CTRL) & BIT23) != 0) {
```
... or some other test to see if the bit is set?

**Comment by kimocoder** [comment]
Thanks, the fix has been applied to the v5.3.4 branch. :1st_place_medal:
