### ISSUE TITLE
support tenda u12 pls

### ISSUE THREAD

**Issue by 687766616e** [aircrack-ng/rtl8812au#313]
add this to `usb_intf.c`?
`{USB_DEVICE(0x2604, 0x0012), .driver_info = RTL8812}, /* Tenda U12 */`

**Comment by Hurricos** [comment]
https://github.com/aircrack-ng/rtl8812au/blob/ac2db9948dba95c975e2b298feaf37a16e532988/os_dep/linux/usb_intf.c#L193

So what you really want is changes applied to v5.2.20 (the current "stable" branch) to be forwarded to v5.3.4; that'll be done eventually on its own.
