### ISSUE TITLE
Unable to change channel using iwconfig

### ISSUE THREAD

**Issue by afk11** [aircrack-ng/rtl8812au#315]
I need to change the cards channel in software, and with other devices I would run `iwconfig wlan0 channel X`

I've since started using the AWUS036ACH and noticed this doesn't work - it stays at 2.412Ghz. 

I ran `iw dev wlan0 scan` and the channel on the device did change, so it mustn't be impossible. 

I did try `iw dev wlan0 set channel X` and `iw phy phy0 set channel X` and both return `command failed: Operation not supported (-95)`

**Comment by kimocoder** [comment]
iwconfig is deprecated.. try using "iw" instead. Have said it before, say it again...
works like a charm..

[output.log](https://github.com/aircrack-ng/rtl8812au/files/3050125/output.log)

**Comment by afk11** [comment]
@kimocoder 

I hope you don't think I've wasted your time opening this issue, but did you read the entire description? I already said I tried that.

> I did try iw dev wlan0 set channel X and iw phy phy0 set channel X and both return command failed:  Operation not supported (-95)

It's also my first time with that tool. What do you suggest when it doesn't work either?

**Comment by kimocoder** [comment]
Ok. Let me Try reproducing it. I've found the IW controls / handlers / implemention code yesterday

**Comment by MrMas** [comment]
Can this issue be reopened or should I open a new issue?

**Comment by afk11** [comment]
open another, this one was spoiled by having two driver sets installed :+1:

**Comment by MrMas** [comment]
Thanks! Sounds good. As it turns out, I've resolved this issue and can set the channel just fine with iw.

**Comment by kimocoder** [comment]
Read the README.md. iwconfig is deprecated, stay to "iw"
