### ISSUE TITLE
iw and iwconfig BOTH unable to change channel

### ISSUE THREAD

**Issue by afk11** [aircrack-ng/rtl8812au#318]
Version of #315 with a better title:
https://github.com/aircrack-ng/rtl8812au/issues/315

I need to change the cards channel in software, and with other devices I would run `iwconfig wlan0 channel X`

I've since started using the AWUS036ACH and noticed this doesn't work - it stays at 2.412Ghz.

I ran `iw dev wlan0 scan` and the channel on the device did change, so it mustn't be impossible.

I also tried `iw dev wlan0 set channel X` and `iw phy phy0 set channel X` and both return command failed: Operation not supported (-95)

**Comment by kimocoder** [comment]
Allways avoid using iwconfig at least.. that one causes trouble for me trying to put them in monitor til, but IW works again. Leave this open I'll dive into ut 😊

**Comment by kimocoder** [comment]
Well, this is how is goes to me, on the same adapter... i may set channels, but scanning is actually off :/
God damn, that needs to be resolved..

**Comment by kimocoder** [comment]
I can set channels, but scanning got issues with that chipset.

* We should check NetworkManager.conf and possible remove some interference  there for a start..
  I start probing the code for diffs

![Screenshot from 2019-04-07 09-41-25](https://user-images.githubusercontent.com/4252297/55680403-74320380-5919-11e9-9c56-1dcb7fd6cdc5.png)

**Comment by kimocoder** [comment]
There are some information about the missing functions [here](https://forum.openwrt.org/t/solved-rtl8188-driver-for-18-06-01/29131/3l)

bbl!

**Comment by kimocoder** [comment]
Utility iw exclusively uses the nl80211 interface.
    some drivers, like RTL8188EU, RTL8188ETV, RTL8188FTV etc. don't implement those ioctls and therefor iw command is not working partially, or at all.

The OpenWrt uses /package/kernel/mac80211/files/lib/netifd/wireless/mac80211.sh to manipulate the WiFi and it's based on iw command.
The major issue in it is that it uses simplified way how to do so. First it removes all the interfaces and that creates them again with the new required setup. Generally it works, when the WiFi driver supports the needed commands, but when not, it fails.
I've solved it with the rewriting of iw commands with old-fasshioned ifconfig, iwconfig commands and it works now. I've modified only the AP functions which I need, but it will work for the other functions too.
I will suggest to include simple test if the WiFi driver supports the iw ioctls, or not and than use the appropriate commands in the mac80211.sh.

**Comment by kimocoder** [comment]
Just pushed this https://github.com/aircrack-ng/rtl8812au/commit/3a4df6e3dcb753d1e53836da2204680baa3ad478

**Comment by kimocoder** [comment]
@afk11 Could you update with "git pull" then "make -j4 && make install" again.. (and of course "modprobe -r 88XXau && modprobe 88XXau" again and test...

**Comment by afk11** [comment]
hey @kimocoder! I just did a clean install of my system with v5.2.20, and this time setting channels is working! The previous setup was pretty old and might've had other drivers installed as well, I'm thinking that was my problem now :/ thanks all the same!

**Comment by kimocoder** [comment]
![IMG_20190408_104322](https://user-images.githubusercontent.com/4252297/55712049-4c609f80-59ee-11e9-9bd9-9a972f091bd8.jpg)

Yeah, thought it was weird..

**Comment by afk11** [comment]
Yea, my bad. Thanks for your work on the driver, and for getting back to me also!
