### ISSUE TITLE
CONFIG_PLATFORM_ARM64_RPI not in Makefile

### ISSUE THREAD

**Issue by bsddemon** [aircrack-ng/rtl8812au#336]
README.md describes that
$ sed -i 's/CONFIG_PLATFORM_ARM64_RPI = n/CONFIG_PLATFORM_ARM64_RPI = y/g' Makefile
needs to be executed RPI 3 B+, but CONFIG_PLATFORM_ARM64_RPI does not exists in the Makefile.

When I compile with
sed -i 's/CONFIG_PLATFORM_ARM_RPI = n/CONFIG_PLATFORM_ARM_RPI = y/g' Makefile
it obviously does not work. How can compile and use the driver for my RPI 3 B+?

**Comment by tomsaul** [comment]
The value is in the 5.2 branch, but not in the 5.3 version.  I have not checked if/where it is used in the code to see if that also reverted, but minimally it should be added back into the Makefile.

**Comment by thewood** [comment]
i second this

**Comment by kimocoder** [comment]
This issue has been resolved.
