### ISSUE TITLE
Driver not loaded for rtl8811CU (0xc811)

### ISSUE THREAD

**Issue by Skallwar** [aircrack-ng/rtl8812au#338]
Hello,

I'm trying to get this driver working with my rtl8811CU dongle, but the driver is not loaded when the device is plugged in

I'm using arch linux with 5.0.8 kernel

**Comment by Skallwar** [comment]
I've try to set CONFIG_RTL8821C = y in the Makefile but it dosen't works

**Comment by Hurricos** [comment]
It is not intended for this device. You are seeing a vestige of the driver's historical source, involving a lot of code shared between a lot of devices in the rtl8xxxu series.

**Comment by kimocoder** [comment]
These drivers supports rtl8812au, (8811au), 8814au a d 8821au, NOT CU adapters.
