### ISSUE TITLE
How the send Deuth packet under Monitor Mode work

### ISSUE THREAD

**Issue by dove1413** [aircrack-ng/rtl8812au#346]
I tested the driver and it could perform Deuth packet with aireplay-ng，But another driver(8811) I was trying to use couldn't send the packet Since the Basic structure seems the same, So I was wondering any clue How this driver implements this feature (Maybe some Document introduce the driver structure? I'm really not familiar with Driver things), And Maybe I could modify my driver by myself so support this feature, Thx

**Comment by kimocoder** [comment]
We support it, don't really have time to explain howto add frame injection, but if you probe through the commits, you will find it though

**Comment by dove1413** [comment]
Very Appreciate about the info :)

**Comment by dove1413** [comment]
It seems with the same frame injection demo program, Under my 8811 driver with log, It even not calling the **rtw_xmit_entry**  function (It did call under other situation like connecting wifi), Instead 8812 will call  **rtw_xmit_entry** and **rtw_monitor_xmit_entry** things, which is a callback registered by **ndo_start_xmit** or other. I'm wondering whether there is a **switch** or **config** affected to this feature so when I run the demo under Monitor Mode  It could call the **rtw_xmit_entry** callback.  Any Insight? @kimocoder

**Comment by cedricbambooza** [comment]
pls consider closing the issue, when it's solved by now :)
