### ISSUE TITLE
Problem with Airgeddon

### ISSUE THREAD

**Issue by bobob15** [aircrack-ng/rtl8812au#350]
Hello, after having put my card in monitor mode manually, it is impossible for me to choose it in Airgeddon, I have an error (see picture). I don't know if it's from the drivers or from Airgeddon itself. No problem with Wifite

Can you help me?

![60715486_2040120692962004_1301917656726634496_n](https://user-images.githubusercontent.com/19501429/58192793-e68c5680-7cc1-11e9-901d-32a84ef26ee3.jpg)

**Comment by Dema323** [comment]
Did you fix it ? Having the same issue

**Comment by kimocoder** [comment]
No, they (Airgeddon) needs to add support, just like aircrack-ng (airmon-ng) did, as these drivers does not support virtual interfaces (VIF).

**Comment by bobob15** [comment]
I found someone who has the same problem on the Airgeddon github but the developer seems to say that it comes from the driver and not from Airgeddon itself

![image](https://user-images.githubusercontent.com/19501429/58422961-39845600-8094-11e9-9f60-907527c94038.png)

**Comment by kimocoder** [comment]
Like in airmon-ng, it should be possible to add checks if device is in monitor mode and go from there. Else there's nothing to do here until the chipsets get into the mac80211 stack

**Comment by Dema323** [comment]
i read the same post thats why i asked if i had the right drivers

**Comment by Dema323** [comment]
[https://www.evilsocket.net/2019/02/13/Pwning-WiFi-networks-with-bettercap-and-the-PMKID-client-less-attack/](url) this guy uses the WSU 1900 and uses the drivers on the aircrack git

**Comment by bobob15** [comment]
![](https://i.imgur.com/W3oiU6r.png)

**Comment by bobob15** [comment]
No way to make it work? 
I notice that it worked on version 5.2.20..

**Comment by bobob15** [comment]
![](https://i.imgur.com/pBWSWSH.png)

**Comment by Dema323** [comment]
nope, i got v5.2.20 on my laptop now and it doesn't work
Don't think we need to expect support on this repo

**Comment by Jo900** [comment]
v5.2.20 is the only that work properly with airgeddon, only if installed with the realtek-rtl88xxau-dkms
let me know if we can see a fix somewhere..
