### ISSUE TITLE
NEW v5.6.4 driver

### ISSUE THREAD

**Issue by kimocoder** [aircrack-ng/rtl8812au#358]
* Needs work to get it working. May take some time, as @fariouche was the one with the skill to make all chipsets in one module

**Comment by kimocoder** [comment]
@fariouche do you got some time to help out on the new branch?
it fixes several things, also the LPS, more info here https://patchwork.kernel.org/patch/10928417/

I'll ship you an unreleased device (prototype) for the work :1st_place_medal:

**Comment by fedux** [comment]
Hi @kimocoder,  

It looks like you made a mistake and merged the new driver into the v5.3.4 branch. See 6c1b4a333b067eaddc9b8b34927019b41b99bc36

**Comment by kimocoder** [comment]
I know, i know... And I don't have time to clean up the mess right now.
will fix it om some days, anyhow there is no doubt on which is more stable and better.

I'll revert the v5.3.4 branch and continue on the v5.6.4 branch when I'm available again

**Comment by kimocoder** [comment]
@fedux Now, I reverted it back again. Thanks for the heads up, sir!

**Comment by satmandu** [comment]
At the moment 5.6.4 is a seamless drop-in for 5.3.4 for a USB-AC56 card on ARM64/RPI 3 B.

**Comment by kimocoder** [comment]
@dema323 @SubaashNair  I'll explain a bit.. the 8812au and 8821au moves forward, new releases popps up, new HAL, phydm.. while the 8814au (AWUS1900) still uses the v5.1.5 HAL with some modifications to fit our 88XXau collection which origins from the 8812au.

Status right now? For 8812au/8821au it's ok, the v5.6.4  will be a good one, but the 8814au still hang behind. At least the HAL and PHYDM is, and they are pretty important in that case.

Realtek has started on a newer mac80211 stack they call "rtw88", perhaps with some negotiation we'll try to convince them to add 8812au, 8821au and 8814au to it, who knows..

Today, these drivers.. is a mix og nl80211/cfg80211 and should be thrown away years ago.. but then I wouldn't sit here writing this novelle either. At least I've learned a lot from it though

Really sad as the device in itself looks pretty awesome with those antennas, right?
Been doing these drivers for some time, and I've learned a lot, but the question I ask myself all the time is.. Realtek... why?? I can't understand why they use chipsets that's poorly supported at all. The drivers should have been ready2go when the chips was sent to first vendor.

**Comment by kimocoder** [comment]
![wavemon](https://user-images.githubusercontent.com/4252297/59571862-50253800-90a9-11e9-930f-276249ae291f.png)


**NMCLI CONNECTION SHOW: OUTPUT**
[nmcli_con_show_output.log](https://github.com/aircrack-ng/rtl8812au/files/3294839/nmcli_con_show_output.log)

**IW PHY# INFO: OUTPUT**
[phy_info_output.txt](https://github.com/aircrack-ng/rtl8812au/files/3294840/phy_info_output.txt)

**nmcli -f GENERAL,WIFI-PROPERTIES dev show wlan#**
GENERAL.DEVICE:                         wlan2
GENERAL.TYPE:                           wifi
GENERAL.NM-TYPE:                        NMDeviceWifi
GENERAL.VENDOR:                         Realtek Semiconductor Corp.
GENERAL.PRODUCT:                        RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter
GENERAL.DRIVER:                         rtl88xxau
GENERAL.DRIVER-VERSION:                 --
GENERAL.FIRMWARE-VERSION:               --
GENERAL.HWADDR:                         00:C0:CA:A4:7B:06
GENERAL.MTU:                            1500
GENERAL.STATE:                          100 (connected)
GENERAL.REASON:                         0 (No reason given)
GENERAL.UDI:                            /sys/devices/pci0000:00/0000:00:1d.7/usb3/3-4/3-4:1.0/net/wlan2
GENERAL.IP-IFACE:                       wlan2
GENERAL.IS-SOFTWARE:                    no
GENERAL.NM-MANAGED:                     yes
GENERAL.AUTOCONNECT:                    yes
GENERAL.FIRMWARE-MISSING:               no
GENERAL.NM-PLUGIN-MISSING:              no
GENERAL.PHYS-PORT-ID:                   --
GENERAL.CONNECTION:                     CYBERSPACE
GENERAL.CON-UUID:                       6eff5aba-1d06-4fa7-8c49-3c5e96d2e799
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/ActiveConnection/2
GENERAL.METERED:                        no (guessed)
WIFI-PROPERTIES.WEP:                    yes
WIFI-PROPERTIES.WPA:                    yes
WIFI-PROPERTIES.WPA2:                   yes
WIFI-PROPERTIES.TKIP:                   yes
WIFI-PROPERTIES.CCMP:                   yes
WIFI-PROPERTIES.AP:                     yes
WIFI-PROPERTIES.ADHOC:                  yes
WIFI-PROPERTIES.2GHZ:                   yes
WIFI-PROPERTIES.5GHZ:                   yes
