### ISSUE TITLE
PLATFORM_ARM_RPI Missing in makefile

### ISSUE THREAD

**Issue by marc-y-marc** [aircrack-ng/rtl8812au#371]
Hi All,

I was running on a RPI 3B+ however i did not have 64 bit OS. Starting from branch 5.3.4 (so also 5.6.4) the PLATFORM_ARM_RPI is missing in the makefile.

PLATFORM_ARM64_RPI is available but gives errors. I added the old rules an the build was succesfull.

So, request is to add 'PLATFORM_ARM_RPI' back in to the makefile.

**Comment by marc-y-marc** [comment]
Oops, i made a small mistake. It is only missing in 5.6.4

The 5.3.4 branch is fine.

**Comment by kimocoder** [comment]
Yeah, lots is missing in v5.6.4 still. Make a PR and it's there and credits goes your way

**Comment by ThijsWithaar** [comment]
Please note #373.

**Comment by kimocoder** [comment]
Merged. Thanks
