### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Kradziej** [aircrack-ng/rtl8812au#372]
I get this when I try to build under armbian

/root/rtl8812au-aircrack/os_dep/linux/os_intfs.c: In function ‘netdev_vir_if_close’:
/root/rtl8812au-aircrack/os_dep/linux/os_intfs.c:2651:2: error: ‘wdev’ undeclared (first use in this function)
  wdev->iftype = NL80211_IFTYPE_MONITOR;
  ^~~~

So code is:
 
#ifdef CONFIG_IOCTL_CFG80211
       wdev->iftype = NL80211_IFTYPE_MONITOR;
       wdev->current_bss = NULL;
	
shouldn't it be like

#ifdef CONFIG_IOCTL_CFG80211
       padapter->rtw_wdev->iftype = NL80211_IFTYPE_MONITOR;
       padapter->rtw_wdev->current_bss = NULL;

or maybe it's not needed at all?

**Comment by kimocoder** [comment]
@Kradziej Sorry the delayed answer.. first off.. which branch are you using? what device/chipset do you have? "lsusb" and "airmon-ng" output would be great.

**Comment by kimocoder** [comment]
This issue should be resolved, please use latest branch

**Comment by michaljurecko** [comment]
@pdp7 

Hi, I have same problem here:
https://github.com/aircrack-ng/rtl8812au/blob/1af7edca86138533d04d7b7eb08a883d9ea4872a/os_dep/linux/os_intfs.c#L2804-L2810

```
/home/user/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8812au-ct-custom-1af7edca/os_dep/linux/os_intfs.c:2805:2: error: 'wdev' undeclared (first use in this function); did you mean 'cdev'?
  wdev->iftype = NL80211_IFTYPE_MONITOR;
  ^~~~
  cdev
```

**Comment by TheJustLink** [comment]
Use the latest branch 5.7.0

**Comment by TheJustLink** [comment]
> 
> 
> Use the latest branch 5.7.0

git clone -b v5.7.0 https://github.com/aircrack-ng/rtl8812au.git
