### ISSUE TITLE
build of v5.6.4 results in make.log error '-mgeneral-regs-only'

### ISSUE THREAD

**Issue by ianburton20** [aircrack-ng/rtl8812au#375]
dkms build of v5.6.4 on Raspi Pi 4.19.42-V7+ results in make.log error gcc: error: unrecognised command line option '-mgeneral-regs-only'

**Comment by ThijsWithaar** [comment]
Related to #371 and https://github.com/aircrack-ng/rtl8812au/pull/373.

**Comment by kimocoder** [comment]
v5.6.4 hasn't really been worked on much yet, but I've got more time soon hopefully
