### ISSUE TITLE
enable CONFIG_IOCTL_CFG80211 in x86, build fail

### ISSUE THREAD

**Issue by LorenzosSummer** [aircrack-ng/rtl8812au#379]
hi dear,
    i found an issue when i enable CONFIG_IOCTL_CFG80211 in x86 platform. it will broken in building. i fix it and support to you.  THANKS for shareing project.

@@ -2633,6 +2633,9 @@ int netdev_vir_if_open(struct net_device *pnetdev)
static int netdev_vir_if_close(struct net_device *pnetdev)
{
_adapter *padapter = (_adapter *)rtw_netdev_priv(pnetdev);
+#ifdef CONFIG_IOCTL_CFG80211
+ struct wireless_dev *wdev = padapter->rtw_wdev;
+#endif

**Comment by kimocoder** [comment]
@crisiscain okey, which branch is this?
