### ISSUE TITLE
Device   RTL8811AU works on 5.3.4 but not on 5.6.4

### ISSUE THREAD

**Issue by minsonj2016** [aircrack-ng/rtl8812au#381]
Device   RTL8811AU works on 5.3.4 but not on 5.6.4

5.6.4 does not 'claim' it .

Bus 002 Device 003: ID 0bda:a811 Realtek Semiconductor Corp. RTL8811AU 802.11a/b/g/n/ac WLAN Adapter

**Comment by kimocoder** [comment]
This branch doesn't support 8811, 8814 and 8821 yet. Need some more work
