### ISSUE TITLE
5.6.4.1 doesnt work correctly on 8811

### ISSUE THREAD

**Issue by davidbepo** [aircrack-ng/rtl8812au#389]
since support for other chipsets was added to 5.6.4.1 i decided to try it, but even tough the device is recognized correctly it doesnt show any networks to connect to

if you want any more details please let me know

**Comment by kimocoder** [comment]
Ok. That's 8821au driver, we'll dive into it shortly

**Comment by davidbepo** [comment]
wow, thanks for the quick reply

**Comment by davidbepo** [comment]
should i retest with the newest commits?

**Comment by kimocoder** [comment]
8814au works... 8821au (8811au) needs some testing/fixes propably.

**Comment by davidbepo** [comment]
just retested it and the same happens

also a thing that i forgot to note is that after reverting to older driver and rebooting the same happens(no networks shown) and it requires to unplug and plug the usb to work (this also happened on the original report)

**Comment by fariouche** [comment]
Just pulled the updates from 5.6.4.1 and it seems there is a regression regarding the support of the 8812 chipset.
Looking at the code, the issue is because of some cleanup
in includes/hal_intf.h, the enum CHIP_TYPE must remain untouched.
This is because this enum is then used somewhere to retrieve the chip type from an array.
Changing the enums here will lead the driver to not correctly detecting the chip.
In the case of the 8812, it was initializing it as a 8188E, and then a big mess happen (incorrect functions called, crashes etc)
Just revert the enum back to its original content is enough.

I believe the problem happens for all the chipsets

**Comment by kimocoder** [comment]
Tested 8812au and 8814au, they are working.. 8821au had issues before i made the cleanup commits though. I cannot seem to find my 8821au adapter, but I'll look harder when I'm back again

**Comment by fariouche** [comment]
forgot to say that I got the issue when testing in AP mode. I didn't looked closer

**Comment by kimocoder** [comment]
@davidbepo update and compile/build/install and report back :+1:

**Comment by davidbepo** [comment]
i did test it and the results were... interesting
even tough i was still unable to connect, this time gnome-shell freaked out, the settings didnt open and weird things happened
so different behavior for sure
if you want any more details please ask

**Comment by KenMacD** [comment]
@kimocoder any update on this? Can I help in testing anything?

Testing on a Kali image they're using `5.2.20`, which works, and `5.6.4.1` does not. I tried to `bisect` where it stops working, but there's a lot of non-working builds on newer kernels in between. One `dmesg` line that looks interesting in some of the `5.6.4` stuff is `rtl8812au_hal_init: Download Firmware failed!!`

**Comment by DrSchottky** [comment]
Tested my RTL8811AU (0bda:a811) and isn't working with 5.6.4.1.
No scan results, no frames received in monitor mode

**Comment by davidbepo** [comment]
retested with latest commit and no network shows up

**Comment by kimocoder** [comment]
Move over to v5.6.4.2 instead of v5.6.4.1

**Comment by davidbepo** [comment]
@kimocoder just tried 5.6.4.2 and still no networks show up :(

**Comment by KenMacD** [comment]
@kimocoder same here, still broken. Did you want to re-open this bug, or should a new one be opened?

**Comment by KenMacD** [comment]
@davidbepo I just tried the latest commits on the `v5.6.4.2` branch (https://github.com/aircrack-ng/rtl8812au/commit/329baeeef7e3b2fca940d8cb9a197aba17fc8319) and a scan worked.

**Comment by davidbepo** [comment]
okay, let me test real quick

**Comment by davidbepo** [comment]
DKMS build error :(

**Comment by davidbepo** [comment]
its the same error on the CI btw
@kimocoder

**Comment by kimocoder** [comment]
@davidbepo update and build again. just fixed it

**Comment by davidbepo** [comment]
its WORKING!

**Comment by davidbepo** [comment]
and i should note that in my brief testing its faster and more stable, but of course more time is required
