### ISSUE TITLE
Description of Makefile 'CONFIG_...' options sought

### ISSUE THREAD

**Issue by beschissen** [aircrack-ng/rtl8812au#392]
I've searched fairly extensively and cannot seem to locate any reliable descriptions or explanations of the various configuration options and CFlags for this driver - **if anyone can point me in the direction of a resource (or resources) which might have this info I would happily amend the appropriate comments to the Makefile in a pull request or a separate document for inclusion here!** 

Any and all help would be appreciated since this is driving me a little nuts right now :weary:.

**Comment by kimocoder** [comment]
Here you go ... https://gcc.gnu.org/onlinedocs/gcc/index.html#SEC_Contents
