### ISSUE TITLE
Monitor Mode For Both 2.4 & 5?  AWUS1900

### ISSUE THREAD

**Issue by bobpiesz** [aircrack-ng/rtl8812au#411]
No matter what I try, I'm having issues with monitor mode only working in either 2.4 or 5.  I cannot seem to pin point as to what is causing this.

My read out:

> wlan1     unassociated  ESSID:""  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=5.22 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=0/100  Signal level=0 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

>

**Comment by kimocoder** [comment]
I can.. the 8814AU is a very different driver from the other supported chipsets.. it's old, buggy, dirty..

**Comment by seeul8er** [comment]
@bobpiesz What command do you use to set the channel/frequency?
I am using v5.6.4.1 with AWUS1900 and set it up as follows:
```bash
   frequency="2427"
   ip link set "$interface" down
   iw dev "$interface" set type monitor
   ip link set "$interface" up
   iw dev "$interface" set freq $frequency
```

Looking at Wireshark live traces: The adapter always forwards a bunch of packets at once and then pauses for some ~30-60 seconds till some new data arrives. Looking at the channel of the received packets it looks like the adapter is looping through all the frequencies (scan mode?).

[AWUS1900_monitor_mode.pcapng.zip](https://github.com/aircrack-ng/rtl8812au/files/3631174/AWUS1900_monitor_mode.pcapng.zip)

**Comment by seeul8er** [comment]
Not sure if is the same issue but running `sudo airmon-ng check kill` killed wpa_supplicant which fixed the channel to what I set it to. Tested on Ubuntu 18.04 Kernel 4.15

**Comment by kimocoder** [comment]
@bobpiesz 

Update to v5.6.4.2 branch :+1: 
Patches has been added and bugs has been squashed!

Closing the issue report, but feel free to re-open or open tickets on other issues. Thanks

![Screenshot from 2019-11-11 20-34-01](https://user-images.githubusercontent.com/4252297/68616127-b2516000-04c4-11ea-86df-802f472fb76b.png)
