### ISSUE TITLE
TP-LINK Archer T9UH Euro v1 slow speeds after driver version 5.2.2

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/rtl8812au#414]
Hi,
Fedora 30, 5.2.9-200.fc30.x86-64

As the title states.
I Have a 100Mbps connection and when using Speedtest, I actually normally get slightly over 100Mbps.
But when using any driver after 5.2.2 I only get ~24Mbps.
Any Ideas
Thanks in advance.

**Comment by SeeLook** [comment]
See this:
https://github.com/aircrack-ng/rtl8812au/issues/327
However reverting doesn't work any more with 5.6.4.1 branch
and with 5.3.1 kernel this branch hangs as hell.

**Comment by kimocoder** [comment]
Update to branch v5.6.4.2. Problems have been resolved and bugs has been squashed!
However, if there's any more issues, please open a new issue report :+1:
