### ISSUE TITLE
Installation fails under Linux Mint 19, kernel 4.15

### ISSUE THREAD

**Issue by cristianav** [aircrack-ng/rtl8812au#419]
Hello,

First of all, many thanks for all your work, much appreciated.

Now, I'm trying to install the drivers but I'm stopped at this step:

```
CC [M]  /var/lib/dkms/rtl8812au/5.6.4.1/build/os_dep/linux/rtw_cfgvendor.o
  CC [M]  /var/lib/dkms/rtl8812au/5.6.4.1/build/os_dep/linux/wifi_regd.o
  CC [M]  /var/lib/dkms/rtl8812au/5.6.4.1/build/os_dep/linux/rtw_android.o
/var/lib/dkms/rtl8812au/5.6.4.1/build/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_indicate_sta_assoc’:
/var/lib/dkms/rtl8812au/5.6.4.1/build/os_dep/linux/ioctl_cfg80211.c:4484:3: error: implicit declaration of function ‘cfg80211_sinfo_alloc_tid_stats’; did you mean ‘cfg80211_inform_bss_width’? [-Werror=implicit-function-declaration]
   cfg80211_sinfo_alloc_tid_stats(&sinfo, GFP_KERNEL);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   cfg80211_inform_bss_width
  CC [M]  /var/lib/dkms/rtl8812au/5.6.4.1/build/os_dep/linux/rtw_rhashtable.o
  CC [M]  /var/lib/dkms/rtl8812au/5.6.4.1/build/os_dep/linux/ioctl_mp.o
  CC [M]  /var/lib/dkms/rtl8812au/5.6.4.1/build/hal/hal_intf.o
  CC [M]  /var/lib/dkms/rtl8812au/5.6.4.1/build/hal/hal_com.o
/var/lib/dkms/rtl8812au/5.6.4.1/build/os_dep/linux/ioctl_cfg80211.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-cast-function-type’
cc1: warning: unrecognized command line option ‘-Wno-cast-function-type’
cc1: some warnings being treated as errors
scripts/Makefile.build:332: recipe for target '/var/lib/dkms/rtl8812au/5.6.4.1/build/os_dep/linux/ioctl_cfg80211.o' failed
make[2]: *** [/var/lib/dkms/rtl8812au/5.6.4.1/build/os_dep/linux/ioctl_cfg80211.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:1552: recipe for target '_module_/var/lib/dkms/rtl8812au/5.6.4.1/build' failed
make[1]: *** [_module_/var/lib/dkms/rtl8812au/5.6.4.1/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-20-generic'
Makefile:1606: recipe for target 'modules' failed
make: *** [modules] Error 2
```

Linux Mint 19 4.15.0-20-generic #21-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

Any idea about this?
Thanks

**Comment by kimocoder** [comment]
Thanks, did you try using "make && make install" instead of DKMS ?

**Comment by cristianav** [comment]
Yes, both ways but the same result. 
Is maybe the compiler too old or something like that?

Thanks for your reply.

⁣Get BlueMail for Android ​

**Comment by kimocoder** [comment]
@CGarces may you add some Linux Mint checks to Travis? Added you to README.md under credits btw 🥇

**Comment by kimocoder** [comment]
I'll fix 1 issue shortly, then Mint check should/will be added to Travis CI for watching. I'll notify you when I push a minor compiler fix

**Comment by CGarces** [comment]
"Mint check"?

I can add checks for some scenarios, but not for one specific distribution. Please point me to the commit that fix this issue and I'll try to understand the problem.

**Comment by kimocoder** [comment]
I have no idea on Travis 😅 I'll boot up a virtual Mint, it's Ubuntu based so it can't be that serious, just don't have more time right away

**Comment by romainreignier** [comment]
I had the exact same error while building this module on a 4.14 kernel.
It appears that the function `cfg80211_sinfo_alloc_tid_stats()` was introduced in 4.18 with [this commit](https://github.com/torvalds/linux/commit/8689c051a20195b228e19acb155c7d6e48a86753).
The v5.3.4 is building on this kernel.
