### ISSUE TITLE
USB wireless Adapter NOT detected after install the driver

### ISSUE THREAD

**Issue by koreaidi0t** [aircrack-ng/rtl8812au#44]
I use TP-link Archer T4U AC1300. Before installing driver, the adapter was detected(I mean that I can see the Deviceid of it after run the command "lsusb")but, after installing the driver, the id quickly disappeared.
But the driver worked few days ago, but now it didn't work. When the driver worked before, I just tried to inject frame, capture packets, and change the txpower to 30. It seemed that everything was OK except changing txpower.
I tried to install some different version of driver, but failed...

I'm sorry for my poor English, and thank you for reading.

**Comment by lion24** [comment]
Hi! 
Try to unload the driver and load it again. 
rmmod 8812au 
insmod 8812au

or via dkms:
dkms remove -m ${MODULE_NAME}/${MODULE_VERSION} --all

**Comment by kimocoder** [comment]
The "lsusb" should show the device (with VID/PID) even when the driver isn't installed. Check your OS setup. Also, try to avoid DKMS at this time, some users are complaining about it not working.

Compile & build manually instead. Check README.
