### ISSUE TITLE
deauth not working :/

### ISSUE THREAD

**Issue by azamet90** [aircrack-ng/rtl8812au#467]
sudo aireplay-ng -9 wlan0
00:28:02  Trying broadcast probe requests...
00:28:04  No Answer...
00:28:04  Found 5 APs

00:28:04  Trying directed probe requests...
00:28:04  D0:6F:82:56:EF:0C - channel: 11 - 'Univision_1320'
00:28:10   0/30:   0%

00:28:10  2E:0E:3D:A6:43:EF - channel: 11 - 'AndroidAP43EF'
00:28:16   0/30:   0%

00:28:16  34:CC:28:00:FA:EC - channel: 11 - 'G-Mobile 8FEF'
00:28:22   0/30:   0%

00:28:22  00:27:22:C8:6A:C0 - channel: 11 - 'KEWIKO_WiFi'
00:28:28   0/30:   0%

00:28:28  00:27:22:8C:48:72 - channel: 11 - 'KEWIKO_WiFi'
00:28:34   0/30:   0%

**Comment by azamet90** [comment]
fixed the problem with uninstalling it and installing from kali  repo

**Comment by nem64** [comment]
This issue should stay open.. I'm experiencing this on multiple machines, even on the latest 5.6.4.2 branch.

**Comment by kimocoder** [comment]
Frame injection isn't working atm. That's why

**Comment by kimocoder** [comment]
Update and it should be working again.

![IMG_20191114_105243](https://user-images.githubusercontent.com/4252297/68846415-59a0e380-06cd-11ea-8a61-b2afbf4c52d3.jpg)

**Comment by azamet90** [comment]
> Update and it should be working again.
> 
> ![IMG_20191114_105243](https://user-images.githubusercontent.com/4252297/68846415-59a0e380-06cd-11ea-8a61-b2afbf4c52d3.jpg)

Also after mod probe it is working you mean?

**Comment by kimocoder** [comment]
For me it does, after reverting a commit. I just pushed an update that fixes injection.

**Comment by azamet90** [comment]
> I just pushed an update that fixes injection.

my english is bad sorry for asking again: you  did not install any extra package just modprobe you did right?


edit:

after modinfo command its working on me too thank you man!


edit:

but i cannot see my txpower signalpower etc...

```
iwconfig
wlan1     IEEE 802.11  ESSID:"AndroidAP43EF"  
          Mode:Managed  Frequency:2.412 GHz  Access Point: 2E:0E:3D:A6:43:EF   
          Bit Rate=144.4 Mb/s   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          Link Quality=60/70  Signal level=-50 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:4   Missed beacon:0

wlan0     unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=0/100  Signal level=0 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

lo        no wireless extensions.

eth0      no wireless extensions.

```

**Comment by kimocoder** [comment]
I haven't added more iw outout yet, but I added txpower control yesterday..

"iw <adapter> info" will give it to you
