### ISSUE TITLE
problems with Alfa awus1900 rtl8814u in virtual machines - ¿usb 3.0 problem?

### ISSUE THREAD

**Issue by gearcapitan** [aircrack-ng/rtl8812au#47]
apparently there are problems with connectivity with virtual machines no matter if it is vmware or virtualbox in both there is problem, the antenna simply does not detect Wi-Fi networks and can not be used even when it is connected to the virtual machine, it has not been able to discover which is the real problem, but a possible solution that I found is the following; dial automatic connection of our alpha antenna to the virtual machine, turn off the computer and turn it back on and turn on our virtual machine the antenna can be connected to wifi networks, however there is another problem, the mondo monitor is very slow and the injection of packages I also leave print imprecations to show more what we do

Main problem in virtual machines occurs equally in vmware and in virtualbox
![kali linux-2017-11-03-16-18-55](https://user-images.githubusercontent.com/13740942/32411479-b5bb995e-c1a0-11e7-9b12-8407b34138d7.png)
![captura de pantalla 110](https://user-images.githubusercontent.com/13740942/32411781-a2545244-c1a9-11e7-9ef8-9db2fc534ff1.png)

mark automatic connection of the device to the virtual machine, then turn off and restart the PC

![captura de pantalla 107](https://user-images.githubusercontent.com/13740942/32411488-018de38c-c1a1-11e7-8ec3-7c39614ab920.png)
![captura de pantalla 108](https://user-images.githubusercontent.com/13740942/32411491-0e429eba-c1a1-11e7-8334-de3848b3f3d2.png)

in both virtual machines the automatic connection is activated

Once the previous thing is done, you have to force the antenna to the monitor mode in the following way because no wifi test application is able to put it automatically, the bad thing is that all the networks of our vm will fall even the eth0, and to top it all. antenna is slow in scanning, detects very few networks and does not inject packets correctly
![captura de pantalla 109](https://user-images.githubusercontent.com/13740942/32411515-e184549e-c1a1-11e7-915c-9a76350d4487.png)

a diference of another antenna that I have old driver rtl8187L

![kali linux-2017-11-04-20-59-34](https://user-images.githubusercontent.com/13740942/32411539-1b041258-c1a3-11e7-8ccc-b1368e8598ee.png)
then I do not know if it is possible some kind of optimization or update that is able to correct this that I am presented and that surely more than one will be happening

**Comment by kimocoder** [comment]
Closed due to two issue reports on the same issue.
