### ISSUE TITLE
V5.6.4.2 doesn't work with Kismet

### ISSUE THREAD

**Issue by ianburton20** [aircrack-ng/rtl8812au#470]
V5.6.4.2 much advanced of late - but it still can't work with Kismet which needs the driver to report packets seen at the 802.11 link layer.

**Comment by kimocoder** [comment]
@ianburton20 Just pushed a frame injection fix. Download, compile/build/install reboot and voilà

![Screenshot from 2019-11-14 10-33-04](https://user-images.githubusercontent.com/4252297/68844703-7f78b900-06ca-11ea-8ad8-b0c34f97bc47.png)

**Comment by ianburton20** [comment]
Thanks. Did a dkms build - but no difference. Still reports no mac80211 controls.

**Comment by kimocoder** [comment]
mac80211 controls? You know this is a cfg80211/nl80211 driver right?

**Comment by ianburton20** [comment]
Thanks again.  Researched cfg82011/nl80211 but don't fully understand it. Just know that V5.6..4.2 does not work with Kismet - and I guess that many would want it to.

**Comment by kimocoder** [comment]
Yeah, it does not support mac80211 (which is newer I/O handlers etc).
