### ISSUE TITLE
Different behavior on different branches - TP Link Archer AC600 

### ISSUE THREAD

**Issue by seppzer0** [aircrack-ng/rtl8812au#479]
I'm trying to get a working wifi driver with PCAP support. The dongle I'm using is TP Link Archer T2U Nano and what's strange about it is that it only works properly with v5.3.4 branch. Both Monitor and Managed modes.

Right now I'm aiming to get a working v5.2.20 driver with it's pcap support. But just like with v5.6.4.1 it both does and does not work. What I mean is that the dongle does get recognised and there are no error messages in the terminal, but in reality the dongle does not respond to any of my requests. For example, I try to connect to my wifi - it just keeps connecting with no result. Or when I scan networks in monitor mode - nothing is displayed.

v5.3.4 works flawlessly. The only issue is, as I mentioned, the lack of pcap.

Is there a way to resolve this? To make a driver with functional pcap?

**Comment by nvixonimo** [comment]
what's wrong with you? cant you just answer the question
