### ISSUE TITLE
still received an error message about: unrecognized command line option .....

### ISSUE THREAD

**Issue by dongdaming1966** [aircrack-ng/rtl8812au#484]
Hi
I am using RP4, have run folloing commands as your README

`$ sed -i 's/CONFIG_PLATFORM_I386_PC = y/CONFIG_PLATFORM_I386_PC = n/g' Makefile`
`$ sed -i 's/CONFIG_PLATFORM_ARM64_RPI = n/CONFIG_PLATFORM_ARM64_RPI = y/g' Makefile`
`$ sed -i 's/^dkms build/ARCH=arm dkms build/' dkms-install.sh`
`$ sed -i 's/^MAKE="/MAKE="ARCH=arm\ /' dkms.conf`

but error message `unrecognized command line option ‘-mgeneral-regs-only’` doesn't disapear.

**Comment by amiramir** [comment]
Same here.

**Comment by James-stdy-app** [comment]
Bump. followed the same steps and get the same result. Hope it gets fixed soon.

EDIT: Never mind I though I had to sudo make && sudo make install, when all I had to do was run kms-install.sh..

So it is actually fixed. just run dams-install rather then making. :)

**Comment by cedricbambooza** [comment]
pls consider closing the issue, when it's solved by now :)
