### ISSUE TITLE
No AP found using v5.6.4.2/v5.6.4.1

### ISSUE THREAD

**Issue by yshui** [aircrack-ng/rtl8812au#499]
A scan shows no results. If I downgrade to v5.3.4, I can see the APs and I can connect to them just fine.

In dmesg, I see lines like:

`RTW: _alloc_mgtxmitframe(wlan0) alloc xmitbuf fail`

```
[ 3645.379145] RTW: ===>PHY_GetTxPowerIndexBase: INVALID Rate(0x02).
[ 3645.379232] RTW: ===>PHY_GetTxPowerIndexBase: INVALID Rate(0x04).
[ 3645.379313] RTW: ===>PHY_GetTxPowerIndexBase: INVALID Rate(0x0b).
```
```
[ 3855.377317] RTW: rtl8812_sreset_linked_status_check REG_RXDMA_STATUS:0xeaeaeaea
[ 3857.510363] RTW: rtl8812_sreset_xmit_status_check REG_TXDMA_STATUS:0xeaeaeaea
[ 3857.510365] RTW: rtl8812_sreset_xmit_status_check tx hang
```

Not sure if they are related.

**Comment by kimocoder** [comment]
OS, kernel, which chipset? (since er got 3)

**Comment by yshui** [comment]
Linux 5.3.13,  T2U Nano

**Comment by NullbutC00L** [comment]
Same problem here zero APs found

**Comment by epinter** [comment]
See issue https://github.com/aircrack-ng/rtl8812au/issues/422 and PR https://github.com/aircrack-ng/rtl8812au/pull/504

**Comment by yshui** [comment]
@epinter I don't think #504 is related, my VID:PID is `2357:011e`

**Comment by yshui** [comment]
Looks like this problem has disappeared from the latest v5.6.4.2 branch. Closing.
