### ISSUE TITLE
Some channels are disabled with latest driver in Ubuntu - 5.3.0-23-generic 

### ISSUE THREAD

**Issue by charliebabbitt1988** [aircrack-ng/rtl8812au#502]
I was testing some channel setting with "sudo iw dev adapter_name set channel 38" and I am getting this error message:

kernel reports: Channel is disabled
command failed: Invalid argument (-22)

I get this error when trying to set the channels to 38, 42, and 46.

It looks like it could be similar to this issue: https://github.com/diederikdehaas/rtl8812AU/issues/35

I tried to test this after upgrading my Ubuntu distro from 19.04 to 19.10.  I am also using an AWUS036ACH adapter.

Under previous kernels and drivers (5.3.4), this worked without a problem.  I'm thinking that this is a kernel issue or some config that was altered during the upgrade process from 19.04 to 19.10.  The driver is probably fine (I could be wrong) because it was working before the upgrade.

Does anyone know how this can be fixed?

**Comment by kimocoder** [comment]
This issue has been resolved. Thanks
