### ISSUE TITLE
Wifi Networks not Showing in awus1900 

### ISSUE THREAD

**Issue by itsmehacker** [aircrack-ng/rtl8812au#508]
I am facing issue in awus1900 wifi adapter having chipset rtl8814u after installing driver wifi network is not showing in airodump or in network manager

Please help

**Comment by cedricbambooza** [comment]
https://github.com/aircrack-ng/rtl8814au 

maybe try that one

**Comment by cedricbambooza** [comment]
pls consider closing the issue, when it's solved by now :)

**Comment by itsmehacker** [comment]
Working fine
