### ISSUE TITLE
getting the AWUS036ACS card to work in monitor mode

### ISSUE THREAD

**Issue by James-stdy-app** [aircrack-ng/rtl8812au#510]
Hi there, 

Just wondering if the AWUS036ACS Alfa card works with monitor mode on a Raspberry Pi Zero?

it uses the rtl8811au chipset. Im really running out of ideas. In the most recent branch, v5.6.4.2 the card turns on and can connect to wifi. However when trying to sniff for packets in monitor mode, there is nothing, like no packets being picked up at all.

Any help or support is REALLY appreciated!

Kind Regards,
James.

EDIT:
The driver v5.6.4.2 works 100% fine! My lack of knowledge led me to believe that there was an issue with the driver. However 1) I have never compiled anything before, 2) The python library failed because for some reason my if statement "hasLayer(Dot11)" was always false, thus not "working".

To reiterate this driver works fine. Thank you to the maintainers of this driver and their VERY useful active support.

**Comment by kimocoder** [comment]
Great! Noted

**Comment by kimocoder** [comment]
@CGarces note to self, Zero working
