### ISSUE TITLE
ASUS USB-AC56 ( RTL8812AU ) aircrack-ng v5.6.4.2 hangs on heavy loads

### ISSUE THREAD

**Issue by imoskovko** [aircrack-ng/rtl8812au#515]
Hello!

ASUS USB-AC56 ( RTL8812AU ) aircrack-ng v5.6.4.2 hangs on heavy loads every hour or several.

Lets say i am copying 20 Gb set of FLAC over SFTP by FileZilla or downloading several 5 Gb torrents. ISP Ethernet line is 100MB/s.

Router is RT-AC68U with latest Merlin Firmware Version:384.13

It happens on every router firmware or on CentOs 7 or current Ubuntu 18. Or on all latest RTL1812AU drivers like 4.2.20 for example. All compiled from source. Also i experience it on at least 2 different Intel motherboards.

How to diagnose it? May be i need to toggle some WIFi settings on router? Please advice what to try

Details:

Happens now on:
https://browser.geekbench.com/geekbench3/8825731
Intel Celeron J1900 @ 2.42 GHz  + 8 Gb RAM + Ubuntu 18.04.3 LTS (latest updates)

and happens last 2 years on:
https://browser.geekbench.com/geekbench3/7885051
Intel Pentium G4400 @ 3.30 GHz + 8 Gb RAM + CentOs v7.< 2019.08 latest updates >

### 
root@htpc3:~# uname -a
Linux htpc3 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

root@htpc3:~# cat /etc/issue
Ubuntu 18.04.3 LTS \n \l

lshw -C network

root@htpc3:~# lshw -C network
  *-network
       description: Wireless interface
       physical id: 1
       bus info: usb@1:2.1
       logical name: wlxd850e6f36050
       serial: d8:50:e6:f3:60:50
       capabilities: ethernet physical wireless
       configuration: broadcast=yes driver=rtl8812au ip=192.168.3.108 multicast=yes wireless=IEEE 802.11AC

 iwconfig

root@htpc3:~#  iwconfig
lo        no wireless extensions.

wlxd850e6f36050  IEEE 802.11AC  ESSID:"igor.home.5"  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency:5.18 GHz  Access Point: 78:24:AF:E5:8A:24
          Bit Rate:867 Mb/s   Sensitivity:0/0
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:****-****-****-****-****-****-****-****   Security mode:open
          Power Management:off
          Link Quality=59/100  Signal level=-66 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

 modinfo 8812au | grep -vE 'parm:|alias:'

root@htpc3:~#  modinfo 8812au | grep -vE 'parm:|alias:'
filename:       /lib/modules/5.0.0-37-generic/kernel/drivers/net/wireless/8812au.ko
version:        v5.6.4.2_35491.20191025
author:         Realtek Semiconductor Corp.
description:    Realtek Wireless Lan Driver
license:        GPL
srcversion:     BEE2C27F4D7318C7028582C
depends:        cfg80211
retpoline:      Y
name:           8812au
vermagic:       5.0.0-37-generic SMP mod_unload

root@htpc3:~# modinfo 88XXau |  grep -vE 'parm:|alias:'
filename:       /lib/modules/5.0.0-37-generic/kernel/drivers/net/wireless/88XXau.ko
version:        v5.6.4.2_35491.20191025
author:         Realtek Semiconductor Corp.
description:    Realtek Wireless Lan Driver
license:        GPL
srcversion:     BC13115196DCDDE07B01F02
depends:        cfg80211
retpoline:      Y
name:           88XXau
vermagic:       5.0.0-37-generic SMP mod_unload

cat ./Makefile | grep -iE '= y'

root@htpc3:~# cat /usr/local/src/asus/rtl8812au/2019/git_5.6.4.2_aircrack/rtl8812au/Makefile  |  grep -iE '= y'
CONFIG_RTL8812A = y
CONFIG_USB_HCI = y
CONFIG_NET_NS = y
CONFIG_MP_INCLUDED = y
CONFIG_EFUSE_CONFIG_FILE = y
CONFIG_LOAD_PHY_PARA_FROM_FILE = y
CONFIG_TXPWR_BY_RATE = y
CONFIG_TXPWR_LIMIT = y
CONFIG_80211W = y
CONFIG_BR_EXT = y
CONFIG_WIFI_MONITOR = y
CONFIG_RTW_NAPI = y
CONFIG_RTW_GRO = y
CONFIG_RTW_NETIF_SG = y
CONFIG_RTW_DEBUG = y
CONFIG_RTW_SDIO_PM_KEEP_POWER = y
CONFIG_MP_VHT_HW_TX_MODE = y
CONFIG_PLATFORM_I386_PC = y
CONFIG_MP_VHT_HW_TX_MODE = y

Thanks for all suggestions!
Igor

**Comment by cedricbambooza** [comment]
pls consider closing the issue, when it's solved by now :)

**Comment by imoskovko** [comment]
It is not solved. 
I got rid of this USB device and do not recommend it as not stable on Linux. 
I am closing it.
