### ISSUE TITLE
feature request: supporting ip namespace

### ISSUE THREAD

**Issue by webarchymeta** [aircrack-ng/rtl8812au#518]
The current driver does not support ip namespace. It can be found following the steps, assuming that the wireless device is `phy0`:
```
sudo ip netns add test
sudo iw phy phy0 set netns name test
```
then one gets
```
command failed: Operation not supported (-95)
```
Some of other kind of wifi devices allow themselves to be moved into separated ip namespaces, however. I am not sure if this is a inherent problem of the hardware or that of the driver ...

This feature can be useful in virtualized environments of nowadays application

**Comment by kimocoder** [comment]
I'll take a look at this issue tomorrow
