### ISSUE TITLE
RTL8812AU in SDU3-P7C3 hub works bad

### ISSUE THREAD

**Issue by vladinko0** [aircrack-ng/rtl8812au#519]
I am using USB-AC56 adapter and when it is connected directly to computers USB3 port it works fine and I can find about 30 Access Points.
But when I plug the adapter to SDU3-P7C3 hub I can find only about 3 Access Points.
I am running it on Kali Linux 2019.3

What can be the problem?

**Comment by kimocoder** [comment]
I need more information.. OS, kernel, dmesg, iwconfig, airmon-ng, lsusb logs.. whatever. Provide more information and re-open if the problem exists anymore
