### ISSUE TITLE
AUR add linux-headers dependency

### ISSUE THREAD

**Issue by arclabs561** [aircrack-ng/rtl8812au#527]
I've just tried installing https://aur.archlinux.org/packages/rtl88xxau-aircrack-dkms-git on 5.4.3-arch1-1, and got the error
```
(2/2) Install DKMS modules
==> Unable to install module rtl88xxau/r990.5a1399b for kernel *: Missing kernel headers.
```
To fix this I additionally installed `linux-headers`, and then re-installed the AUR.

Looking at the PKGBUILD I see that it only includes `dkms`. We should add `linux-headers` to the dependencies. I'd be happy to add a pull request if pointed in the right direction.

**Comment by logan001** [comment]
i think you are not posting in the right place. you should probably post on aur page
