### ISSUE TITLE
5.2.9.3 version

### ISSUE THREAD

**Issue by Goga777** [aircrack-ng/rtl8812au#53]
do you plan to update this branch as it was done here is https://github.com/gordboy/rtl8812au ?

**Comment by kimocoder** [comment]
Not at this time as we're not using the v5.2.9/5.2.9.3 for penetration testing purposes anyway.
The v5.2.9 is for 8812 only, we rely on having them both (as in v5.1.5)

However, we're well aware of gordboy's v5.2.9.3 bringing several crash fixes + KRACK attack fix (AP mode), that is how/why we porter it over to v5.1.5 (",)
