### ISSUE TITLE
When is the next release/long term

### ISSUE THREAD

**Issue by weedkiller** [aircrack-ng/rtl8812au#546]
Hi can you please consider a release its been over a yr.

**Comment by kimocoder** [comment]
Nope it's not, latest release is from december 2019, don't use releases, use branches. Closed

**Comment by weedkiller** [comment]
ok thanks, you may want to tag it here.

https://github.com/aircrack-ng/rtl8812au/releases shows Dec 2018

**Comment by kimocoder** [comment]
The README explains the most of it, don't use releases..
