### ISSUE TITLE
 Any chance of getting virtual interface now

### ISSUE THREAD

**Issue by usama7628674** [aircrack-ng/rtl8812au#551]
@kimocoder The virtual interface can be created by using `iw phy phy0 interface add mon0 type managed` or `iw wlan0 interface add mon0 type monitor` but the interface does nothing.You cant launch hostapd,airodump and mdk4/aireplay.

The only solution is get 2 adapters to lauch AP and injection on different interfaces.

**Comment by kimocoder** [comment]
This driver doesn't support VIF (virtual interfaces), and yes it does, both monitor mode and frame injection is working. Follow the README.
