### ISSUE TITLE
Network Manager won't connect to AP (latest 5.6.4.2 DKMS, kernel 5.4.13, Alfa AWUS036ACH) FT: Invalid group cipher (0)

### ISSUE THREAD

**Issue by crispywizard** [aircrack-ng/rtl8812au#552]
root@unspecified:/home/xor# dkms status
lime-forensics, 1.9-1, 5.4.0-kali3-amd64, x86_64: installed
rtl8812au, 5.6.4.2, 5.4.0-kali3-amd64, x86_64: installed
root@unspecified:/home/xor# uname -a
Linux unspecified 5.4.0-kali3-amd64 #1 SMP Debian 5.4.13-1kali1 (2020-01-20) x86_64 GNU/Linux

This is a recurring problem since Kali 2019.4 and all versions of this driver I have tried.
Clicking on network icon and selecting multiple AP's with known good passphrases fail and the window to re-enter passphrase repeatedly opens.  This occurs even when AP is set to 'Open' with no passphrase required.
-Connecting via terminal works (as detailed in https://www.linuxbabe.com/ubuntu/connect-to-wi-fi-from-terminal-on-ubuntu-18-04-19-04-with-wpa-supplicant)

-Connecting through NetworkManager icon with alternate adapter (Dlink WUA-2340/ar5523) works.

Syslog of the failure (see `FT: Invalid group cipher (0)`): [syslog.txt](https://github.com/aircrack-ng/rtl8812au/files/4145695/syslog.txt)

Screenshot of WireShark FT
![beacon](https://user-images.githubusercontent.com/59219990/73617918-280f2880-45e9-11ea-9000-344fe489f4b3.jpg)

Zipped pcap of beacon: [brutality-beacon.zip](https://github.com/aircrack-ng/rtl8812au/files/4145744/brutality-beacon.zip)

May be related to issue #540

**Comment by kimocoder** [comment]
Move over to #540 please.
