### ISSUE TITLE
AWUS1900 not capturing any targets in Kali Linux?

### ISSUE THREAD

**Issue by LoafyCodes** [aircrack-ng/rtl8812au#559]
I'm trying to use the tool "airodump-ng" with my Alfa AWUS1900 Wi-Fi adapter (rtl8814au) on Kali Linux, in VirtualBox. The adapter is recognized and I am able to put the card into monitor mode. However, the issue is that I am not receiving any output/targets when running the command "airocrack-ng wlan0", while the device is in monitor mode. I followed all instructions listed here.

![airodump](https://user-images.githubusercontent.com/60683198/74404314-56f67d00-4de7-11ea-9815-bbd7b5ec3623.PNG)

I have tried on a Live USB bootable of Kali Linux, and it worked!? I was able to receive targets like how I should be able too. But I need it to work in VirtualBox. Anyone know what the issue is? Let me know if more info/screenshots are needed.

![dmesg](https://user-images.githubusercontent.com/60683198/74493613-ccb62380-4e8f-11ea-8c26-ddba52cd950a.PNG)
![uname](https://user-images.githubusercontent.com/60683198/74494309-de98c600-4e91-11ea-8009-159f2447f051.PNG)
![lsusb](https://user-images.githubusercontent.com/60683198/74494312-e193b680-4e91-11ea-8a81-4e1ab33662e2.PNG)
![network](https://user-images.githubusercontent.com/60683198/74404448-c4a2a900-4de7-11ea-887d-08d031a0d9e4.PNG)
![settings](https://user-images.githubusercontent.com/60683198/74404449-c53b3f80-4de7-11ea-9ad4-c2c43f9c252c.PNG)

**Comment by LoafyCodes** [comment]
Provided more information and screenshots.

**Comment by iMoD1998** [comment]
Had the same issue when selecting specific channel. Try using the latest version of the driver. It seemed to fix it. However, the latest driver is pretty unstable and doesnt wanna work with things like bettercap and wifite because its got problems with iwconfig.

**Comment by iMoD1998** [comment]
Also if you're on the latest version, i noticed that it being in a USB3 port made it not detect as many things as it does in a USB2.

**Comment by kimocoder** [comment]
I'll force it back to USB2 tomorrow, anyhow, Kali hasn't packed the latest driver, so it doesn't support the kernel

**Comment by LoafyCodes** [comment]
Thank you for all the work you put in @kimocoder!
I've been using the AWUS1900 on a Live USB and it works perfectly!

**Comment by kimocoder** [comment]
Just added some parches and fixes to the driver.
There's a brand new 8814AU and 8821AU firmware coming spon :+1: 

```
git clone https://github.com/aircrack-ng/rtl8812au -b v5.6.4.2
cd rtl8812au
make -j4 && make install
```

**Comment by kimocoder** [comment]
And VirtualBox needs the drivers in VM software installed, VMWARE also, and I know it's been trouble all the way.. will take a look later sometime

**Comment by Swiffers** [comment]
I'm having the same issue here. Unable to find any network with the latest drivers on VirtualBox + AWUS1900 (rtl8814au).

**Comment by Joemoma1337** [comment]
Good day all,
I have just gotten my Alfa AWUS1900 (RTL8814AU) and i've only gotten it to get into monitor mode, view networks, connect to networks but i am unable to capture handshakes or deauth devices (to then capture handshakes).

Has there been any updates to this?

running Kali: 5.9.0-kali5-amd64 #1 SMP Debian 5.9.15-1kali1

Merry Christmas all!

**Comment by error404-personnotfound** [comment]
> Good day all,
> I have just gotten my Alfa AWUS1900 (RTL8814AU) and i've only gotten it to get into monitor mode, view networks, connect to networks but i am unable to capture handshakes or deauth devices (to then capture handshakes).
> 
> Has there been any updates to this?
> 
> running Kali: 5.9.0-kali5-amd64 #1 SMP Debian 5.9.15-1kali1
> 
> Merry Christmas all!

Have you got this to work? facing the same issue.... Or is it a problem with kali?

**Comment by cyrus104** [comment]
@kanishkapillai 

There was a driver updated and the RTL8814AU was split and being maintained separately. 

https://github.com/aircrack-ng/rtl8814au
