### ISSUE TITLE
build issue  - rtx_xmit error

### ISSUE THREAD

**Issue by brandontict** [aircrack-ng/rtl8812au#565]
**OS** 
Kali
5.4.0-kali3-amd64. Updated daily . 

Having issue during compiling latest branch, error happens around 

**rtl8812au-5.6.4.2/core/rtw_xmit.o**

Log can be found here , https://pastebin.com/ZCnZrY34  . 

EDIT: 
compiling and installing rtl8812au-5.6.4.1  worked . 

Wonder what the issue is with latest ?

**Comment by kimocoder** [comment]
Branch v5.6.4.2 works just fine.

![Screenshot_20200308-042429](https://user-images.githubusercontent.com/4252297/76156033-c749a300-60f4-11ea-8b20-fe9c7dfa41fa.jpg)
