### ISSUE TITLE
Monitor Mode HT40

### ISSUE THREAD

**Issue by LeeTiK** [aircrack-ng/rtl8812au#585]
Is it possible on the AWUS036ACH adapter to use the 40Mhz band in the monitor for scanning in 2.4Ghz, that is, to receive data from 2 channels simultaneously?

**Comment by bakwc** [comment]
Hi! Did you find the way to use HT40 / HT80 in monitor mode?

**Comment by dzervas** [comment]
Try `sudo iw dev wlp5s0f1u2 set channel 9 HT40+`
