### ISSUE TITLE
MAC address is changing on every plugin

### ISSUE THREAD

**Issue by samiux** [aircrack-ng/rtl8812au#60]
The MAC address of the USB dongle (rtl8812au) is keeping change on every plugin.

**Comment by kcdtv** [comment]
That does not have anything to do with the drivers you use... :smiley_cat: 
Check your network manager configuration and system.d rules if you are not happy about that
I personally wouldn't change anything as a random and non-static mac address is a basic and simple way to help protect your privacy.

**Comment by samiux** [comment]
Agreed.

**Comment by samiux** [comment]
Since the MAC address always changing, I cannot test the dongle on my ARP spoofing protected network.  

Is a switch to control it possible?
