### ISSUE TITLE
How to enable 80 mhz in ap mode

### ISSUE THREAD

**Issue by CMCCAdmin** [aircrack-ng/rtl8812au#610]
I use create_ap to set the ap mode. Only up to 40 mhz ac (400Mbps) can be enabled, how do I enable 80mhz (866Mbps)

root@raspberrypi:/home/pi# cat /etc/create_ap.conf 
CHANNEL=149
GATEWAY=192.168.111.111
WPA_VERSION=2
ETC_HOSTS=0
DHCP_DNS=gateway
NO_DNS=0
NO_DNSMASQ=0
HIDDEN=0
MAC_FILTER=0
MAC_FILTER_ACCEPT=/etc/hostapd/hostapd.accept
ISOLATE_CLIENTS=0
SHARE_METHOD=nat
IEEE80211N=1
IEEE80211AC=1
HT_CAPAB=[HT40+]
VHT_CAPAB=
DRIVER=nl80211
NO_VIRT=0
COUNTRY=AU
FREQ_BAND=5
NEW_MACADDR=
DAEMONIZE=0
NO_HAVEGED=0
WIFI_IFACE=wlan1
INTERNET_IFACE=eth0
SSID=AP
PASSPHRASE=12345678
USE_PSK=0

**Comment by semidark** [comment]
Maybe there is a hint in the README.md of the repository, where this driver was forked from...

https://github.com/astsam/rtl8812au

it describes the iw parameters to set the Channel and the Channelwidth to 80mhz:

> Set channel 149, width 80 MHz:
> 
> $ sudo iw wlan0 set freq 5745 80 5775
