### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by WirthmU** [aircrack-ng/rtl8812au#670]
I get the following error in my RPI:

make ARCH=arm CROSS_COMPILE= -C /lib/modules/5.4.50-v7+/build M=/opt/rtl8812au  modules
make[1]: *** /lib/modules/5.4.50-v7+/build: No such file or directory.  Stop.
Makefile:2245: recipe for target 'modules' failed
make: *** [modules] Error 2

Any help to this?

**Comment by ghost** [comment]
install kernel headers search google

**Comment by kimocoder** [comment]
Read the README.md
