### ISSUE TITLE
any chance for new updates for windows?

### ISSUE THREAD

**Issue by 0lm** [aircrack-ng/rtl8812au#720]
hi all
the chance might be very low, but i wanted to ask anyways.
i have a AWUS036ACH by Alfa Network and it exactly used the rtl8812au drivers. and on linux, it works perfectly. my problem is windows 10. when i install the wpa3 drivers offered by alfa networks, occassionally i get the Evnt ID 11006 error a few times a day. the wpa2 drivers on the other hand are stable. but i would like to be able to use wpa3. but yeah, i suffer these reconnect issues. it is not because of my router. that error only occurs on windows 10 when wpa3 drivers are installed. i have no idea why and how to solve it. my connection is always stable but these occassional short disconnects labled as ID 11006 are annoying.
anyone has experience with that?

EDIT: the error event id i get in wlan-autoconfig in windows 10 event viewer: 
it starts with 11004 (wirless security stopped)
and then 11010 (wireless security started) 
and switches between 11004 and 10010 like 10 times for the next 15 sec
until the 11006 ID comes up (Reason: Dynamic key exchange did not succeed within configured time)
after that, it reconnects to the wlan.

sorry to ask window srelation question here. but somehow windows users have no idea and cant solve this. and since i use linux myself and it totally works over there without problems, i thought i would try.

**Comment by nomadmzl** [comment]
The latest drivers are [here](https://files.alfa.com.tw/?dir=%5B1%5D%20WiFi%20USB%20adapter/AWUS036ACH)

**Comment by 0lm** [comment]
> 
> 
> The latest drivers are [here](https://files.alfa.com.tw/?dir=%5B1%5D%20WiFi%20USB%20adapter/AWUS036ACH)

Thanks for the answer. I already had the latest drivers installed. Thats the reason why I tried here. I cant seem to solve the problem and there is no way to find out where the roots of this errors are. I hoped a driver update could work but only good drivers I can find are for Linux. The Windows ones are currently bound to Realtek's mercy. So I was curious if it would be theoretically possible to compile these for windows.

**Comment by nomadmzl** [comment]
Have you looked at the [reason codes](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc727757(v=ws.10)?redirectedfrom=MSDN) for that eventID?

**Comment by 0lm** [comment]
> 
> 
> Have you looked at the [reason codes](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc727757(v=ws.10)?redirectedfrom=MSDN) for that eventID?

I actually did, but my reason codes do not exist there. for ID 11006 it is 0x48005. By now the error messages changed after Windows cumultative update a few days ago. now i actually ID 11004, (wlan security stopped), before the error event id 8002 appears with the reason code 229378, which is also not existing on the event id 8002 page of microsoft. I basically get reason codes which are not registered or logged in microsoft info pages, so i cant find out the root.
and all hints kinda lead to the drivers. i did have these problems years ago with the wpa3 drivers. so i sticked with the wpa2 drivers which never causes problems. but since they updated the wpa3 drivers end of 2019 agian and i can finally use wpa3, i wanted to try out and get these kind of errors. the frequency of these erros luckily went down, but yeha, they still occur like 1 or 2 times a day.

**Comment by kimocoder** [comment]
We dont to Windows here.. sorry
