### ISSUE TITLE
problem kernel 4.14.0-kali1

### ISSUE THREAD

**Issue by gearcapitan** [aircrack-ng/rtl8812au#73]
root@kali:~# cd rtl8812au/
root@kali:~/rtl8812au# make RTL8814=1
/bin/sh: 1: bc: not found
make -j 4 ARCH=i386 CROSS_COMPILE= -C /lib/modules/4.14.0-kali1-686-pae/build M=/root/rtl8812au  modules
make[1]: se entra en el directorio '/usr/src/linux-headers-4.14.0-kali1-686-pae'
/bin/sh: 1: bc: not found
  Building modules, stage 2.
/bin/sh: 1: bc: not found
  MODPOST 1 modules
make[1]: se sale del directorio '/usr/src/linux-headers-4.14.0-kali1-686-pae'

**Comment by kimocoder** [comment]
"apt-get install bc"
