### ISSUE TITLE
Wrongly claims to support USB ID 0x2357:0x0115 (TP-Link Archer T4U V3)

### ISSUE THREAD

**Issue by patrakov** [aircrack-ng/rtl8812au#731]
This driver contains a line in `os_dep/linux/usb_intf.c`:

```
	{USB_DEVICE(0x2357, 0x0115), .driver_info = RTL8812}, /* TP-Link - Archer T4U AC1300 */
```

However, this also matches the "TP-Link Archer T4U V3" device, which uses a different chipset (RTL8822B) and therefore doesn't work at all (cannot bring the interface up, operation not permitted). If there is indeed some device with USB ID 0x2357:0x0115 that works with this driver, please make the match more specific, so that TP-Link Archer T4U V3 is excluded. Otherwise, please remove this line.

I have verified that TP-Link Archer T4U V3 works with https://github.com/cilynx/rtl88x2bu, and they do this instead:

```
	{USB_DEVICE_AND_INTERFACE_INFO(0x2357, 0x0115, 0xff, 0xff, 0xff), .driver_info = RTL8822B}, /* TP-Link Archer T4U V3 */
```

There is also https://github.com/ulli-kroll/rtw88-usb which specifically mentions TP-Link Archer T4U V3, I haven't tested it. If one expands the RTK_USB_DEVICE macro in that driver, one will see that they match only on `USB_DEVICE(0x2357, 0x0115)` and don't take the interface info into account.

**Comment by nikallian** [comment]
Thy this one too https://github.com/RinCat/RTL88x2BU-Linux-Driver
