### ISSUE TITLE
Manually Compile and install the driver Problem

### ISSUE THREAD

**Issue by mehmetyldz87** [aircrack-ng/rtl8812au#737]
Hi,
I am encountering the error that I gave the screenshot below and I can not use EW-7811UAC.

OS: Ubuntu 18.04.05LTS

![Manual Build](https://user-images.githubusercontent.com/7778498/94911093-46962e00-04ae-11eb-8524-b2e81ee529ad.png)

Building result 

![Selection_002](https://user-images.githubusercontent.com/7778498/94911152-6299cf80-04ae-11eb-8113-b0d9caa71275.png)

**Comment by kimocoder** [comment]
These errors does not affect the drivers, Im aware of them already
