### ISSUE TITLE
Makefile is garbage

### ISSUE THREAD

**Issue by S4RK0Z1** [aircrack-ng/rtl8812au#744]
Whoever did change the ./dkms-install.sh method to this Makefile garbage, ty. Install was a piece of cake with the ./dkms-install.sh method. Right now I wasted 1 1/2 hours to try to get this Makefile work with no avail. Thank you for fcking up a perfectly working/unbroken thing to an unworking garbage.

**Comment by kimocoder** [comment]
So you used 1,5 hours to write "make dkms_install" ?
Congrats!

**Comment by isneverdead** [comment]
can you send me the code?

> Whoever did change the ./dkms-install.sh method to this Makefile garbage, ty. Install was a piece of cake with the ./dkms-install.sh method. Right now I wasted 1 1/2 hours to try to get this Makefile work with no avail. Thank you for fcking up a perfectly working/unbroken thing to an unworking garbage.

hi, can you send me the code please?
