### ISSUE TITLE
Change readme to instruct to install with DKMS via Makefile

### ISSUE THREAD

**Issue by erer1243** [aircrack-ng/rtl8812au#747]
Hi, just a small thing. Was trying to install and got confused by the instruction to run `sudo ./dkms-install.sh`. Looks like that functionality was recently moved into the Makefile as the target dkms_install. Same for the uninstall script being moved to the dkms_remove target. I suggest changing the readme to reflect that. 

Thanks for the driver :^)

**Comment by hifihedgehog** [comment]
Exactly. That really confused me. The new way to install and uninstall via DKMS is the following:

> make dkms_install

...and:

> make dkms_remove

**Comment by hackingking466** [comment]
```
root@kali:~/Downloads/rt# make dkms_install
make: *** No rule to make target 'dkms_install'.  Stop.

``
thats what it gives, it dont install it. what should i write?
