### ISSUE TITLE
Install and Remove scripts are unavailable.

### ISSUE THREAD

**Issue by MG-RX93** [aircrack-ng/rtl8812au#754]
Why were the install and remove scripts removed?

**Comment by hifihedgehog** [comment]
Use make:

https://github.com/aircrack-ng/rtl8812au/issues/747

They embedded the scripts into the makefile but forgot to update the README. Now, run either make dkms_install or make dkms_remove.

**Comment by shimpeif** [comment]
I did "make dkms_install" in rtl8812au directory but failed,
wondering I did it in the wrong directory.
Is there anyone who has successfully made it?

**Comment by kimocoder** [comment]
Yes.. many times, many

**Comment by kimocoder** [comment]
$ git pull
$ make clean && make dkms_install

**Comment by shimpeif** [comment]
> $ git pull
> $ make clean && make dkms_install

I have successfully installed the driver following your instructions.
Thanks.

**Comment by MG-RX93** [comment]
Thanks, this works. Appreciate your help.

**Comment by Tomaszu97** [comment]
There is still a part of readme mentioning this:
`$ sed -i 's/^dkms build/ARCH=arm dkms build/' dkms-install.sh`
I guess since this file does not exist anymore we can prepend the make command like:
`ARCH=arm make dkms_install` ?

**Comment by MG-RX93** [comment]
> There is still a part of readme mentioning this:
> `$ sed -i 's/^dkms build/ARCH=arm dkms build/' dkms-install.sh`
> I guess since this file does not exist anymore we can prepend the make command like:
> `ARCH=arm make dkms_install` ?

That should probably solve the issue for people who are expecting to find the install scrips.
