### ISSUE TITLE
v5.6.4.2 + rtl8811au can not inject short packets 

### ISSUE THREAD

**Issue by 1yura** [aircrack-ng/rtl8812au#758]
It is can inject probe requests with 
aireplay-ng --test
airodump-ng -x
but 
aireplay-ng --deauth
does not work. The other adapter in monitor mode does not see these packets.  It seems v5.6.4.2 + rtl8811au  can not transmit packets less than 30 bytes. 
v5.7.0 + rtl8811au - can not inject at all in monitor mode - is it ok?

**Comment by 1yura** [comment]
solved https://github.com/kimocoder/rtl8812au-5.9.3.2

**Comment by kimocoder** [comment]
I moved it to here

https://github.com/aircrack-ng/rtl8812au/tree/v5.7.0
