### ISSUE TITLE
Kali 2020.3  rtl8812au  problem 

### ISSUE THREAD

**Issue by LuckyFishGeek** [aircrack-ng/rtl8812au#775]
I can attack 2.4G wifi after using the following steps

ifconfig wlan0 down
iwconfig wlan0 mode monitor
ifconfig wlan0 up

But unable to attack 5G wifi
Has any friend encountered the same problem as me?
The chip is rtl8812au

In addition, neither Fluxion nor wifiphisher can use the network card of this chip.

**Comment by vitorinux** [comment]
Check this driver, for me works on slackware kernel 5.4.73

https://github.com/morrownr/8812au

version: 8812au = v5.9.3.2_37279.20201012
vermagic: 5.4.73-slackware SMP

**Comment by LuckyFishGeek** [comment]
> Check this driver, for me works on slackware kernel 5.4.73
> 
> https://github.com/morrownr/8812au
> 
> version: 8812au = v5.9.3.2_37279.20201012
> vermagic: 5.4.73-slackware SMP

thanks  I‘ll try it
