### ISSUE TITLE
wrong build instructions OR dkms-install.sh not in repository

### ISSUE THREAD

**Issue by joaquinabian** [aircrack-ng/rtl8812au#782]
Notes for Raspberry Pi indicate to call:

`$ sed -i 's/^dkms build/ARCH=arm dkms build/' dkms-install.sh`

however **_dkms-install.sh_** is gone from the repository

**Comment by mroliveira7** [comment]
Same happens here.
I download the zip instead of cloning the repo to have the scripts.

**Comment by hrustaddesignllc** [comment]
@mroliveira7 good call downloading zip. I ran into the same issue. I just ran the second command in that section and the build & install worked. However, I still have yet to see if the driver is actually working.
