### ISSUE TITLE
[Solved] dkms fails with error code 10 on Kernel 5.10.3 Arch (old commit was used)

### ISSUE THREAD

**Issue by cedricbambooza** [aircrack-ng/rtl8812au#803]
can't compile kernel module through dkms on new kernel on arch system

DKMS make.log for rtl88xxau-r1123.e9fbf5c for kernel 5.10.3-arch1-1 (x86_64)
Thu 31 Dec 2020 13:49:47 CET
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.10.3-arch1-1/build M=/var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build  modules
make[1]: Entering directory '/usr/lib/modules/5.10.3-arch1-1/build'
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_io.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_ieee80211.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_mlme.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_mlme_ext.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_mi.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_wlan_util.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_vht.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_pwrctrl.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_rf.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_chplan.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_recv.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_sta_mgt.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_ap.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/mesh/rtw_mesh.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_xmit.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_p2p.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_rson.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_tdls.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_br_ext.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_iol.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_sreset.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_btcoex_wifionly.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_btcoex.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_beamforming.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_odm.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_rm.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/rtw_rm_fsm.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/core/efuse/rtw_efuse.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/osdep_service.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/linux/os_intfs.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/linux/usb_intf.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/linux/usb_ops_linux.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/linux/ioctl_linux.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/linux/xmit_linux.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/linux/mlme_linux.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/linux/recv_linux.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/linux/ioctl_cfg80211.o
  CC [M]  /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/linux/wifi_regd.o
/var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/osdep_service.c: In function ‘isFileReadable’:
/var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/osdep_service.c:2201:11: error: implicit declaration of function ‘get_fs’; did you mean ‘get_sa’? [-Werror=implicit-function-declaration]
 2201 |   oldfs = get_fs();
      |           ^~~~~~
      |           get_sa
/var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/osdep_service.c:2201:11: error: incompatible types when assigning to type ‘mm_segment_t’ from type ‘int’
/var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/osdep_service.c:2203:3: error: implicit declaration of function ‘set_fs’; did you mean ‘sget_fc’? [-Werror=implicit-function-declaration]
 2203 |   set_fs(KERNEL_DS);
      |   ^~~~~~
      |   sget_fc
/var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/osdep_service.c:2203:10: error: ‘KERNEL_DS’ undeclared (first use in this function); did you mean ‘KERNFS_NS’?
 2203 |   set_fs(KERNEL_DS);
      |          ^~~~~~~~~
      |          KERNFS_NS
/var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/osdep_service.c:2203:10: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/osdep_service.c: In function ‘retriveFromFile’:
/var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/osdep_service.c:2243:12: error: incompatible types when assigning to type ‘mm_segment_t’ from type ‘int’
 2243 |    oldfs = get_fs();
      |            ^~~~~~
/var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/osdep_service.c:2245:11: error: ‘KERNEL_DS’ undeclared (first use in this function); did you mean ‘KERNFS_NS’?
 2245 |    set_fs(KERNEL_DS);
      |           ^~~~~~~~~
      |           KERNFS_NS
/var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/osdep_service.c: In function ‘storeToFile’:
/var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/osdep_service.c:2282:12: error: incompatible types when assigning to type ‘mm_segment_t’ from type ‘int’
 2282 |    oldfs = get_fs();
      |            ^~~~~~
/var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/osdep_service.c:2284:11: error: ‘KERNEL_DS’ undeclared (first use in this function); did you mean ‘KERNFS_NS’?
 2284 |    set_fs(KERNEL_DS);
      |           ^~~~~~~~~
      |           KERNFS_NS
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:279: /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/os_dep/osdep_service.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1805: /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.10.3-arch1-1/build'
make: *** [Makefile:2246: modules] Error 2

Output while running pacman -U looks like this:

sudo pacman -U rtl88xxau-aircrack-dkms-git-r1123.e9fbf5c-1-x86_64.pkg.tar.zst
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) rtl88xxau-aircrack-dkms-git-r1123.e9fbf5c-1

Total Installed Size: 50.86 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring [###############################################################] 100%
(1/1) checking package integrity [###############################################################] 100%
(1/1) loading package files [###############################################################] 100%
(1/1) checking for file conflicts [###############################################################] 100%
(1/1) checking available disk space [###############################################################] 100%
:: Processing package changes...
(1/1) installing rtl88xxau-aircrack-dkms-git [###############################################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Install DKMS modules
==> dkms install --no-depmod -m rtl88xxau -v r1123.e9fbf5c -k 5.10.3-arch1-1
Error! Bad return status for module build on kernel: 5.10.3-arch1-1 (x86_64)
Consult /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/make.log for more information.
==> Warning, `dkms install --no-depmod -m rtl88xxau -v r1123.e9fbf5c -k 5.10.3-arch1-1' returned 10
==> depmod 5.10.3-arch1-1

I tried the version directly from github with dkms and with make install, both work flawlessly.
Seems like the issue only appears with the dkms version directly from the AUR.

EDIT: was using an old commit, nevermind!

**Comment by cedricbambooza** [comment]
Output while running pacman -U looks like this: 


[neo@bladerunner rtl88xxau-aircrack-dkms-git]$ sudo pacman -U rtl88xxau-aircrack-dkms-git-r1123.e9fbf5c-1-x86_64.pkg.tar.zst 
[sudo] password for neo: 
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) rtl88xxau-aircrack-dkms-git-r1123.e9fbf5c-1

Total Installed Size:  50.86 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                            [###############################################################] 100%
(1/1) checking package integrity                                                                          [###############################################################] 100%
(1/1) loading package files                                                                               [###############################################################] 100%
(1/1) checking for file conflicts                                                                         [###############################################################] 100%
(1/1) checking available disk space                                                                       [###############################################################] 100%
:: Processing package changes...
(1/1) installing rtl88xxau-aircrack-dkms-git                                                              [###############################################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Install DKMS modules
==> dkms install --no-depmod -m rtl88xxau -v r1123.e9fbf5c -k 5.10.3-arch1-1
Error! Bad return status for module build on kernel: 5.10.3-arch1-1 (x86_64)
Consult /var/lib/dkms/rtl88xxau/r1123.e9fbf5c/build/make.log for more information.
==> Warning, `dkms install --no-depmod -m rtl88xxau -v r1123.e9fbf5c -k 5.10.3-arch1-1' returned 10
==> depmod 5.10.3-arch1-1

**Comment by cedricbambooza** [comment]
tried the version directly from the github repo, that works well even though I haven't installed it through dkms.
So maybe the version from the AUR needs updating ^^

**Comment by iyanmv** [comment]
Please close this issue. @cedricbambooza is not using the latest commit and AUR package is fine.

**Comment by cedricbambooza** [comment]
Sorry my bet then ^^ 
can I close the issue myself?
