### ISSUE TITLE
Please add frequecy

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/rtl8812au#817]
is it possible to add frequency  from  5340-5480?

**Comment by astsam** [comment]
Try this patch for v5.6.4.2.
[0001-Add-missing-5GHz-channels.txt](https://github.com/aircrack-ng/rtl8812au/files/5866557/0001-Add-missing-5GHz-channels.txt)

**Comment by ghost** [comment]
> Try this patch for v5.6.4.2.
> [0001-Add-missing-5GHz-channels.txt](https://github.com/aircrack-ng/rtl8812au/files/5866557/0001-Add-missing-5GHz-channels.txt)

Hello Thanks for taking an interest in the speech, where and how do I apply this file?

**Comment by astsam** [comment]
1. Download the source code of the branch v5.6.4.2 (see section [Notes](https://github.com/aircrack-ng/rtl8812au#notes)).
2. Apply the patch
`patch -p1 < 0001-Add-missing-5GHz-channels.txt`
3. [Build and install](https://github.com/aircrack-ng/rtl8812au#make) the driver or use [DKMS](https://github.com/aircrack-ng/rtl8812au#dkms).

**Comment by ghost** [comment]
> 1. Download the source code of the branch v5.6.4.2 (see section [Notes](https://github.com/aircrack-ng/rtl8812au#notes)).
> 2. Apply the patch
>    `patch -p1 < 0001-Add-missing-5GHz-channels.txt`
> 3. [Build and install](https://github.com/aircrack-ng/rtl8812au#make) the driver or use [DKMS](https://github.com/aircrack-ng/rtl8812au#dkms).

THANKS ENDLESS !!! finally everything works 
Thanks again I hope the aircrack-ng team adds your default patch.
Thanks.

**Comment by ghost** [comment]
Is it possible to enable other frequencies?

**Comment by astsam** [comment]
Technically this is possible, but the driver tunes some undocumented registers depending on RF band. Due to the lack of the documentation this modification may cause suboptimal performance in the extended frequency range.

**Comment by Zanzaux** [comment]
Hello astsam  If you can enable  them I would be curious to carry out some tests perhaps adding from 4900 to 5175,

**Comment by astsam** [comment]
I can try to enable 5075 to 5175 frequency range.

**Comment by Zanzaux** [comment]
> I can try to enable 5075 to 5175 frequency range.


Okay thanks, even if I get lower performance I don't care, I have to test some antennas and I'm on non-standard frequencies (4900,5010,5060,5340,5920,5940,6000)

Thanks again

**Comment by astsam** [comment]
[0002-Add-low-frequency-5GHz-band.txt](https://github.com/aircrack-ng/rtl8812au/files/5882288/0002-Add-low-frequency-5GHz-band.txt)
It will be great if you check the real RF output with a spectrum analyzer.

**Comment by ghost** [comment]
Thanks astsam :), let's see if I can do some tests with the spectrum analyzer this weekend. 
I noticed that when I set the channel under 5180 by typing iwconfig
I detect channel "0", which does not happen with the other channels , where the set channel is shown like 5180,5200,5500 etc ...

airodump-ng wlan1 -C 5100
iwconfig
wlan1 unassociated ESSID: "" Nickname: "<WIFI @ REALTEK>"
  Mode: Monitor **Channel = 0** Access Point: Not-Associated

**Comment by astsam** [comment]
I used iw command to set and get channel. You are right, iwconfig has incorrect output.
```
$sudo iw wlx000f00371234 info
Interface wlx000f00371234
	ifindex 58
	wdev 0x3700000001
	addr 00:0f:00:37:12:34
	type monitor
	wiphy 55
	channel 15 (5075 MHz), width: 20 MHz, center1: 5075 MHz
	txpower 20.00 dBm
```
```
$ sudo iwconfig wlx000f00371234
wlx000f00371234  unassociated  ESSID:""  Nickname:"<WIFI@REALTEK>"
          Mode:Monitor  Channel=0  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=0/100  Signal level=0 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```
I supposed the iwconfig is deprecated and see no reason to fix this issue. Try to use the iw utility.

**Comment by Zanzaux** [comment]
Thanks astsam, I made some tests through "airodump-ng wlan1 -C ch" here are the values ​​I get by varying the frequencies from the AP

-52 4920
-48 4950
-1 4970
-45 4990
-1 5010 (don't detected ap) Freq 5010] [Elapsed: 12 s] [fixed frequency wlan1: 2417  (important channel***)
-1 5060
-45 5075
-41 5090

-44 5100
-34 5130
-34 5160
-34 5180

-33 5320
-33 5380
-33 5460
-33 5500

-43 5700
-39 5785

-42 5925
-42 5950
-42 5990
-42 6000

here is also the reg domain file I used
        (2400 - 2494 @ 20), (N / A, 30), (N / A)
        (4920 - 4995 @ 80), (N / A, 33), (N / A)
        (5000 - 5145 @ 80), (N / A, 33), (N / A)
        (5150 - 5465 @ 80), (N / A, 33), (N / A)
        (5470 - 5885 @ 160), (N / A, 33), (N / A)
        (5900 - 6100 @ 160), (N / A, 33), (N / A)
        (57000 - 66000 @ 2160), (N / A, 40), (N / A)

If you can add from 4920-5070 it would be the top !!!
Thank you so much for creating the patch driver and most of all Thanks for the amazing help and availability.

**Comment by astsam2** [comment]
I am happy that my patches help you.
Zanzaux, will you clarify the meaning of the first values
```
-45 5075
...
```

**Comment by astsam2** [comment]
> If you can add from 4920-5070 it would be the top

It is not clear for me how to support this range. The drive internally uses channel number instead of frequency.  Channels from 1 to 14 is reserved for 2,4GHz band. Moreover, due to this formula frequency less than 5000 MHz corresponds to negative channel value.
```
Freq = (Chan * 15) + 5000
```
Therefore, the lowest frequency that could be added is 5075 MHz (corresponding to channel 15).

**Comment by Zanzaux** [comment]
> Sono felice che i miei cerotti ti aiutino.
> Zanzaux, chiarirai il significato dei primi valori
> 
> ```
> -45 5075
> ...
> ```
Se ti riferisci ai primi valori come  4920,4950,4970,4990,5010,5060 li avevo menzionati se potevano essere aggiunti in una delle tue incredibili patch :)  :)  :)

**Comment by Zanzaux** [comment]
> Sono felice che i miei cerotti ti aiutino.
> Zanzaux, chiarirai il significato dei primi valori
> 
> ```
> -45 5075
> ...
> ```

If you refer to the first values ​​like 4920,4950,4970,4990,5010,5060 I had mentioned them if content be added in one of your amazing patches :) :) :)

**Comment by Zanzaux** [comment]
> > If you can add from 4920-5070 it would be the top
> 
> It is not clear for me how to support this range. The drive internally uses channel number instead of frequency. Channels from 1 to 14 is reserved for 2,4GHz band. Moreover, due to this formula frequency less than 5000 MHz corresponds to negative channel value.
> 
> ```
> Freq = (Chan * 15) + 5000
> ```
> 
> Therefore, the lowest frequency that could be added is 5075 MHz (corresponding to channel 15).

I understand, I noticed that through airodump-ng by setting the frequency 5010 it is shown to me as channel "2" which as you say belongs to 2.4 instead the frequency 4970 is shown as channel "15" do not worry I'm sure that if you will find the right documentation you will have no problems enabling them :) you have really done a lot for me congratulations and thanks !!!

**Comment by astsam2** [comment]
`If you refer to the first values ​​like 4920,4950,4970,4990,5010,5060 I had mentioned them if content be added in one of your amazing patches :)`
I am afraid my patch is not ensure the exact equality the desired frequency and the real frequency in the band below channel 36. I cannot check this myself because I have not a proper measurement equipment.

**Comment by Zanzaux** [comment]
Hi astsam I will do an analysis with the spectrum analyzer, since I have never created an access point via linux and network card, do you have any program to advise me on how to create it?

**Comment by Zanzaux** [comment]
Hi astsam I will do an analysis with the spectrum analyzer

**Comment by ghost** [comment]
Unfortunately I am having problems in creating an access point via linux under channel 36, if I insert the channels above 36 more I can create an access point, I have tried both with the linux manager and with hostapd-dnsmasq.
Do you have any solution?

**Comment by astsam2** [comment]
The driver has some checks in ap logic that I missed. Will you try this patch?
[0001-Fix-error-creating-an-access-point-below-channel-36.txt](https://github.com/aircrack-ng/rtl8812au/files/5935155/0001-Fix-error-creating-an-access-point-below-channel-36.txt)

**Comment by astsam2** [comment]
To send frames you may use scapy and a script like this. It sends ProbeRequest frames via mon0 interface.
```
#!/usr/bin/env python3
from scapy.all import *
from scapy.layers.dot11 import *

def main():
    receiver_mac = 'ff:ff:ff:ff:ff:ff'
    # bssid = receiver_mac
    bssid = '03:bb:bb:bb:bb:bb'
    transmitter_mac = '00:22:12:34:56:78'
    ssid = '12345678'
    channel = chr(11)
    iface = 'mon0'
    frame_count = 1000

    frame = RadioTap() \
            / Dot11(type=0, subtype=4, addr1=receiver_mac, addr2=transmitter_mac, addr3=bssid) \
            / Dot11ProbeReq() \
            / Dot11Elt(ID='SSID', info=ssid) \
            / Dot11Elt(ID='Rates', info='\x82\x84\x8b\x96\x0c\x12\x18') \
            / Dot11Elt(ID='ESRates', info='\x30\x48\x60\x6c') \
            / Dot11Elt(ID='DSset', info=channel)
#    answer = srp1(frame, iface=iface)
#    wireshark(frame)

    # send frame_count frames
    # sendp(frame, iface=iface, inter=0.100, count=frame_count)

    # send frames indefinitely
    sendp(frame, iface=iface, inter=0.100, loop=1)

# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    main()
```

**Comment by ghost** [comment]
> The driver has some checks in ap logic that I missed. Will you try this patch?
> [0001-Fix-error-creating-an-access-point-below-channel-36.txt](https://github.com/aircrack-ng/rtl8812au/files/5935155/0001-Fix-error-creating-an-access-point-below-channel-36.txt)

installing the patch and then the driver via dkms when restarting the network card was no longer present, i just downloaded your driver with the patch applied from your repository and now the access point under channel 36 works,

https://github.com/astsam2/rtl8812au

**Comment by Zanzaux** [comment]
Here is the measurement:

CH 48 5240 -52
CH 46 Disable by hostpad
CH 44 5220 -51
CH 42 Disable by hostpad
CH 40 5200 -58
CH 38 Disable by hostpad

UNDER CH 36

CH 36 5180 -54
CH 32 5160 -56
CH 28 5140 -60
CH 24 5120 -58
CH 20 5100 -62
CH 18 5090 -63
Ch 17 5085 -61
CH 16 5080 -61
CH 15 5075 -61

**Comment by Zanzaux** [comment]
Hi astsam typing "iw list" I arrive at the frequency of 5885, but I noticed that I can actually test up to 6000 mhz, could you add the remaining 100 mhz?

**Comment by ghost** [comment]
> > If you can add from 4920-5070 it would be the top
> 
> It is not clear for me how to support this range. The drive internally uses channel number instead of frequency. Channels from 1 to 14 is reserved for 2,4GHz band. Moreover, due to this formula frequency less than 5000 MHz corresponds to negative channel value.
> 
> ```
> Freq = (Chan * 15) + 5000
> ```
> 
> Therefore, the lowest frequency that could be added is 5075 MHz (corresponding to channel 15).

Hello congratulations for the incredible work, finally a driver with a reputable frequency list. I don't know if it can be useful but by scanning the channel for example 2327 I can "start" a deauth on an access point on the frequency of 4920, I don't know if the attack actually comes completed ...

Here is a list of the possible frequencies I have tested
4920 2327 4925 2332 4960 2367 4970 2377 4975 2382 4980 2387

I hope you will be able to increase the frequency range further.
Thanks.

**Comment by lnvlna** [comment]
I got the start with 5080, what about 5000, 5020, 5040, 5060, any ideas, even if I completely disable 2.4? if you look at the formula, I can't use 0 for 5000, that is, at least 1 = 5005, and then 4 = 5020, 8 = 5040, 12 = 5060
