### ISSUE TITLE
Can't connect 5Ghz network

### ISSUE THREAD

**Issue by MarceloZapatta** [aircrack-ng/rtl8812au#831]
Hello!

I'm having an issue, I can't connect to 5Ghz network, only to 2Ghz. In the 5Ghz keep asking to put password or just show "configuring interface". Sometimes I was able to connect to the 5 but I really don't know how to debug the connection, I'm trying to connect via KDE Network Interface.

Sometimes I see more than one network of the same wireless, can it be related?

![image](https://user-images.githubusercontent.com/39474221/107980456-12c02e80-6f9f-11eb-9f12-650fbadcbc9d.png)

I'm on KDE Plasma, linux kernel 4.19

Can you guys help me?

Thanks

**Comment by ghost** [comment]
+1 . Having the same issue

4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

**Comment by MarceloZapatta** [comment]
I was able to connect by fixing the channel in the router settings, now it is on 153.
I think that was the problem. 

But I don't try again on this package, ended up using the: https://github.com/gnab/rtl8812au
