### ISSUE TITLE
Not able to detect my AC600 Archer T2U Plus dongle

### ISSUE THREAD

**Issue by deva-gopalani** [aircrack-ng/rtl8812au#854]
After I run the command `sudo make && make install` i get the following error:

> install -p -m 644 88XXau.ko  /lib/modules/5.8.0-50-generic/kernel/drivers/net/wireless/
> install: cannot create regular file '/lib/modules/5.8.0-50-generic/kernel/drivers/net/wireless/88XXau.ko': Permission denied
> make: *** [Makefile:2253: install] Error 1

can someone please help me solve this? i am working on ubuntu 20.04

**Comment by Bee1To** [comment]
Suddenly make  && suddenly make install

**Comment by Bee1To** [comment]
Sudo make && sudo make install

**Comment by deva-gopalani** [comment]
thanks for the reply @Bee1To but actually my issue has been resolved

**Comment by Sopheaktra2050** [comment]
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.10.0-kali7-amd64/build M=/home/hacker/Desktop/rtl8812au  modules
make[1]: *** /lib/modules/5.10.0-kali7-amd64/build: No such file or directory.  Stop.
make: *** [Makefile:2244: modules] Error 2


                           How to solve this problem sir !
