### ISSUE TITLE
Difference in functionality between “iwconfig” and “iw” to manage interfaces.

### ISSUE THREAD

**Issue by cup-of-coffee-m8** [aircrack-ng/rtl8812au#862]
On using the aircrack suite with different wireless cards, there is an obvious difference between the functionality of the tool when using "iw" compared with "iwconfig", the most notable being channel-hopping.

Can anyone explain why we see these differences? I know the README instructs users to use "ip and iw", but the reasons aren't stated - I'm just really interested as to why! 

Many thanks.

**Comment by ZerBea** [comment]
iw is using preferred NETLINK while iwconfig is using ioctl() system calls.

You can verify this by running iw in debug mode:
```
$ sudo iw --debug wlp39s0f3u1u1u1 set type monitor
-- Debug: Sent Message:
--------------------------   BEGIN NETLINK MESSAGE ---------------------------
  [NETLINK HEADER] 16 octets
    .nlmsg_len = 36
    .type = 33 <0x21>
    .flags = 5 <REQUEST,ACK>
    .seq = 1621337152
    .port = 1644232944
  [GENERIC NETLINK HEADER] 4 octets
    .cmd = 6
    .version = 0
    .unused = 0
  [PAYLOAD] 16 octets
    08 00 03 00 03 00 00 00 08 00 05 00 06 00 00 00 ................
---------------------------  END NETLINK MESSAGE   ---------------------------
-- Debug: Received Message:
--------------------------   BEGIN NETLINK MESSAGE ---------------------------
  [NETLINK HEADER] 16 octets
    .nlmsg_len = 36
    .type = 2 <ERROR>
    .flags = 256 <ROOT>
    .seq = 1621337152
    .port = 1644232944
  [ERRORMSG] 20 octets
    .error = 0 "Erfolg"
  [ORIGINAL MESSAGE] 16 octets
    .nlmsg_len = 16
    .type = 33 <0x21>
    .flags = 5 <REQUEST,ACK>
    .seq = 1621337152
    .port = 1644232944
---------------------------  END NETLINK MESSAGE   ---------------------------
```

NETLINK and ioctl() system calls are explained here:
https://en.wikipedia.org/wiki/Netlink
https://en.wikipedia.org/wiki/Ioctl

Also read about the difference between them here:
https://stackoverflow.com/questions/11501527/ioctl-vs-netlink-vs-memmap-to-communicate-between-kernel-space-and-user-space

I prefer ioctl() system calls:
```
$ sudo hcxdumptool -m wlp39s0f3u1u1u1
setting interface wlp39s0f3u1u1u1 to monitor mode
```
or
```
$ sudo hcxlabgetmall -m wlp39s0f3u1u1u1
monitor mode activated
```
Most of the Realtek drivers (rtl8812, rtl8814) depend on NETLINK, so using iw in combination with ip is proposed.
