### ISSUE TITLE
Cannot install on latest version of kali linux | Error 1

### ISSUE THREAD

**Issue by Aholicknight** [aircrack-ng/rtl8812au#863]
<img width="628" alt="Screen Shot 2021-05-21 at 6 52 50 PM" src="https://user-images.githubusercontent.com/7843719/119209758-bec55a00-ba65-11eb-9f9d-98857461f7a7.png">

Every time I try to install this on the latest version of kali linux this error pops up, does anyone know how to fix it? Thanks.

**Comment by LinkerOK** [comment]
Use the latest branch 5.7.0

**Comment by LinkerOK** [comment]
> 
> 
> Use the latest branch 5.7.0

git clone -b v5.7.0 https://github.com/aircrack-ng/rtl8812au.git

**Comment by yelsanya** [comment]
Kinda not sure about your version being the latest one, consider running this:
`sudo apt update && sudo apt upgrade`
Also for your issue it seems like you need this
`sudo apt-get install linux-headers-$(uname -r)`
Also do not forget to reboot your machine after that
