### ISSUE TITLE
Make Error on Default Branch 

### ISSUE THREAD

**Issue by Illusion-1404** [aircrack-ng/rtl8812au#883]
Getting Make Error on default branch ,

System Configuration: Ubuntu 18.04  Kernel Version : 5.11.5

make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.11.5-051105-generic/build M=/home/octo-ws/Downloads/rtl8812au  modules
make[1]: Entering directory '/usr/src/linux-headers-5.11.5-051105-generic'
  LD [M]  /home/octo-ws/Downloads/rtl8812au/88XXau.ko
ld:scripts/module.lds:6: ignoring invalid character `#' in expression
ld:scripts/module.lds:6: syntax error
scripts/Makefile.modfinal:58: recipe for target '/home/octo-ws/Downloads/rtl8812au/88XXau.ko' failed
make[3]: *** [/home/octo-ws/Downloads/rtl8812au/88XXau.ko] Error 1
scripts/Makefile.modpost:117: recipe for target '__modpost' failed
make[2]: *** [__modpost] Error 2
Makefile:1710: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.11.5-051105-generic'
Makefile:2244: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by kimocoder** [comment]
This is not driver related issue.
