### ISSUE TITLE
Error when compiling (an c file has a input/output error)

### ISSUE THREAD

**Issue by trizziprogrammer** [aircrack-ng/rtl8812au#890]
I'm new to Linux and I want to start my Linux journey.

I have EndeavourOS installed on my main machine but it has no wifi. Whenever I install with DKMS in the directory of the latest source code, it gives me the following error:

```
mkdir -p /usr/src/8812au-5.6.4.2_35491.20191025
cp
-r * /usr/src/8812au-5.6.4.2_35491.20191025
cp:
error reading 'core/mesh/rtw_mesh.c': Input/output error
make: *** [Makefile:2302: dkms_install] Error 1
```

An working solution for me would help start my Linux journey, I use Windows 10 to that time I sent this issue, and oh! My linux kernel is 5.13.12.

**Comment by kimocoder** [comment]
This is not driver related issue.
