### ISSUE TITLE
New 8812au and 8811au (8821au) Drivers Available

### ISSUE THREAD

**Issue by morrownr** [aircrack-ng/rtl8812au#897]
To the owner of this repo: I can forward clean copies or you can clone my repos if you are interested.

All, I have new repos available for the 8812au and 8811au (8821au). They are based on fresh code and need to be tested.

[8812au-20210629](https://github.com/morrownr/8812au-20210629)

[8821au-20210708](https://github.com/morrownr/8821au-20210708)

The reason for 2 repos is that the driver for the 8812au and 8811au chipsets have been broken into 2 separate drivers. That happened over a year ago. So make sure you get the right driver. I keep a file in each repo called ```supported-device-IDs``` that should help you confirm which driver you need.

Myself and a couple of other individuals have conducted basic managed mode, master mode and monitor mode testing but wider testing and reporting is needed. Anyone wishing to help manage the repos should contact me as I maintain several repos which takes a lot of time. Regards.

**Comment by kimocoder** [comment]
Im well aware. Anyhow, our drivers which is aiming towards penetration testing got frame injection capabilities and for the moment I got no time to put together all 'new' drivers of 8812, 8821 and 8814 atm.

**Comment by kimocoder** [comment]
And our base is pure Realtek releases, not newer  different tagged vendor versions popping up after Realtek closed their ftp for the public, not that I know which ones you got without checking

**Comment by morrownr** [comment]
> Im well aware. Anyhow, our drivers which is aiming towards penetration testing got frame injection capabilities and for the moment I got no time to put together all 'new' drivers of 8812, 8821 and 8814 atm.

Christian,

I understand about people that have limited time. I spent most of my life working long hours. I am retired these days so have a little extra time for hobbies. I'm not asking you to put together anything. I'm actually offering assistance. I've had repos for the 8812au and 8821au up since last year and am somewhat familiar with penetration testing. I was contacted last year by a couple of resellers that support folks that use Kali and Parrot. I have worked with them. Results are very good.

The new repos that I opened today are based on clean code that Edimax slid into their support site about 4 weeks ago. I've been testing both along with supporting files that I have worked on over the last year. The new 8821au driver is damn good and far better than previous. I have tested both for frame injection and deauth support. I have tested both on kernels up to and including 5.15. I'm sure there can be improvements to the code and if you see a way forward for this to be a collaborative effort that is fine. If not, that is fine also.

Regards

Nick

**Comment by markschechter** [comment]
Hi Nick, 

Not sure if this is the best place to put this but I've been struggling with your installation script & I was hoping you might be able to point me in the right direction? 

I've been trying to install this driver package but I keep getting the following error. I've been trying to get it to work for a few days now. 

`Raspberry Pi OS (64 bit) support was turned on in Makefile as planned.`

I have checked the makefile & toggled the flags for the respective 64 & 32 bit builds. No luck. 

I am running: 
`Linux my-pi 5.10.74-v8+ #1471 SMP PREEMPT Mon Oct 18 17:11:19 BST 2021 aarch64 GNU/Linux`

As far as my experience is concerned, I'd say I am a moderate Linux user, not a noob, but not an expert. 

Many thanks
M

**Comment by morrownr** [comment]
Mark,

It would be better if you go over to the following repo since you indicate you are using a driver from my site:

https://github.com/morrownr/8812au-20210629

When you get there, post your problem and we will take it from there.

Nick
