### ISSUE TITLE
TP-LINK Archer T9UH (2357:0106)

### ISSUE THREAD

**Issue by ValZapod** [aircrack-ng/rtl8812au#9]
https://github.com/ScrambledAuroras/rtl8814AU/commit/44134fa948510afa9da37471fd33d87815a59742
Please add this commit to your code.

**Comment by kimocoder** [comment]
Give me 5 minutes to review this sir, then it will be added :)

**Comment by ValZapod** [comment]
https://wikidevi.com/w/index.php?title=TP-LINK_Archer_T9UH&oldid=155068 and i have this dongle myself, if it would be of any help.

**Comment by kimocoder** [comment]
This device/adapter is already added. Please use the "v5.1.5" not the "master" as the v5.1.5 is the branch with the newest driver & the best support.

**Comment by ValZapod** [comment]
Yes(( I haven't seen it.
