### ISSUE TITLE
Make fails on Fedora 34 running Kernel v 5.15-rc5

### ISSUE THREAD

**Issue by githubris** [aircrack-ng/rtl8812au#900]
Make has failed on all linux-5.15 release candidates including the current 5.15-rc5

make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.15.0-rc5/build M=/SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au  modules
make[1]: Entering directory '/root/KERNELS/linux-5.15-rc5'
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_cmd.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_security.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_debug.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_io.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_ioctl_query.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_ioctl_set.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_ieee80211.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_mlme.o
/SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_mlme.c: In function ‘rtw_drv_scan_by_self’:
/SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_mlme.c:3196:17: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
 3196 |                 else
      |                 ^~~~
/SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_mlme.c:3199:25: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
 3199 |                         goto exit;
      |                         ^~~~
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_mlme_ext.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_mi.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_wlan_util.o
/SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_wlan_util.c: In function ‘rtw_parse_sta_vendor_ie_8812’:
/SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_wlan_util.c:3226:25: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
 3226 |                         for(i=0; i<9;i++)
      |                         ^~~
In file included from /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/include/drv_types.h:51,
                 from /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_wlan_util.c:17:
/SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/include/rtw_debug.h:52:33: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
   52 |         #define RTW_INFO(x,...) do {} while (0)
      |                                 ^~
/SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_wlan_util.c:3228:33: note: in expansion of macro ‘RTW_INFO’
 3228 |                                 RTW_INFO("\n");
      |                                 ^~~~~~~~
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_vht.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_pwrctrl.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_rf.o
/SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_rf.c: In function ‘dump_txpwr_lmt’:
/SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_rf.c:775:9: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  775 |         if (IS_HARDWARE_TYPE_JAGUAR_AND_JAGUAR2(adapter))
      |         ^~
In file included from /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/include/drv_types.h:51,
                 from /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_rf.c:17:
/SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/include/rtw_debug.h:220:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  220 |         do {\
      |         ^~
/SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_rf.c:777:17: note: in expansion of macro ‘RTW_PRINT_SEL’
  777 |                 RTW_PRINT_SEL(sel, "txpwr_lmt_5g_20_40_ref:0x%02x\n", rfctl->txpwr_lmt_5g_20_40_ref);
      |                 ^~~~~~~~~~~~~
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_chplan.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_recv.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_sta_mgt.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_ap.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/mesh/rtw_mesh.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_xmit.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_p2p.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_rson.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_tdls.o
  CC [M]  /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_br_ext.o
/SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_br_ext.c:20:18: fatal error: net/ipx.h: No such file or directory
   20 |         #include <net/ipx.h>
      |                  ^~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:277: /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au/core/rtw_br_ext.o] Error 1
make[1]: *** [Makefile:1868: /SEAGATE_03/RTL8812AU-REALTEK-WIFI-AIRCRACK/rtl8812au] Error 2
make[1]: Leaving directory '/root/KERNELS/linux-5.15-rc5'
make: *** [Makefile:2244: modules] Error 2

**Comment by CGarces** [comment]
Please apply patch #898 to fix the error.
And feel free to send a PR to fix the misleading-indentation warnings

**Comment by githubris** [comment]
Thank you very much @CGarces, the patch works!

**Comment by kimocoder** [comment]
More kernel v5.15+ patches has been pushed. Update and build/install.

**Comment by githubris** [comment]
Thanks Christian. Much appreciated.

#middlekey

________________________________
