### ISSUE TITLE
Status of that repository related to other forks

### ISSUE THREAD

**Issue by buhtz** [aircrack-ng/rtl8812au#916]
This repo has a lot of forkes and is also forked from other ones. The fork-network is chaos.

It seams that your repo is the freshest and most active one.

If you have information's about the other repos it would be great if you could point that out in your README.md so that it is easier for new visitors to decide which repo to use. The wiki/howto/blog postings on the internet about RTL8812 are using different repos. They do not help here.

**EDIT**: Also the differences between the AU, CU etc suffixed would help.

**Comment by kimocoder** [comment]
This is mainly for Kali Linux usages, not the newest drivers, but it has monitor mode and frame injection support.
Besides that, we also merged rtl8821au and rtl8814au into the codebase. Thats the difference.
