### ISSUE TITLE
Disable MAC randomization without NetworkManager? (iwd)

### ISSUE THREAD

**Issue by phisch** [aircrack-ng/rtl8812au#920]
I have been struggling to figure out how one would disable the MAC randomization on a system that uses iwd (https://iwd.wiki.kernel.org/) without NetworkManager.
Please let me know if you have any idea!

**Comment by barkawa** [comment]
You can configure MAC randomization in your `/etc/iwd/main.conf`.
Look for AdressRandomization `man iwd.config`.

**Comment by phisch** [comment]
@barkawa thank you! I can't believe I didn't figure that out myself, that's embarrassing.
