### ISSUE TITLE
Virtual interface

### ISSUE THREAD

**Issue by usama7628674** [aircrack-ng/rtl8812au#93]
Does this driver support virtual interface as most of the wifi tools need this feature to work properly?

**Comment by kimocoder** [comment]
no i does not support virtual interface, an you are correct. this impact usage of airmon-ng.
the code is there, but isn't fixed or maintained. it should be a priority so i leave this report open for others to see.

**Comment by kimocoder** [comment]
Here is provided a commit that almost works, it just needs to be finished up.

https://github.com/astsam/rtl8812au/pull/26

**Comment by usama7628674** [comment]
@kimocoder Yeah it's there but it doesn't work yet properly.

**Comment by vanrzuf** [comment]
@kimocoder and how is work going on this? any chances to make it work soon?

**Comment by kimocoder** [comment]
will try some fixes soon, it's not top priority at this point, as it works fine with setting it manually.

**Comment by vanrzuf** [comment]
@kimocoder how it can be done manually? It would be nice if it will work with fluxion :D

**Comment by usuarionuevor** [comment]
@vanrzuf fluxion (which is just a forked and renamed [linset](https://github.com/vk496/linset)) doesn't even support 5ghz... use [airgeddon](https://github.com/v1s1t0r1sh3r3/airgeddon) it support 5ghz already and works with rtl8812au drivers.

**Comment by vanrzuf** [comment]
@usuarionuevor which drivers willa worki without airgeddon? IT cannot switch to monitor mode when chosen on script, need to set IT manually and IT fails in evil twin attack. I'm using dkms drivers

**Comment by kimocoder** [comment]
Found some even more interesting stuff for adding "virtual interface" support.
These 2 commits were made to a v4.3.21 astsam fork. Don't have the time to test it (or port it for testing) at this time, but here they are.

https://github.com/cristi28/rtl8812au/commit/b4f97ee5bd323006b80a0a93a33052e175341c32

https://github.com/cristi28/rtl8812au/commit/7200f38cb27f83ee9a2b19985427244108387799

**Comment by jarilaos** [comment]
@vanrzuf [airgeddon](https://github.com/v1s1t0r1sh3r3/airgeddon) has a new release. Now it works with  airmon  non compatible cards, even with the evil twin attack.

**Comment by kimocoder** [comment]
Next release of the aircrack-ng (with airmon-ng) will have support for this driver.

**Comment by v1s1t0r1sh3r3** [comment]
Hi, I'm one of the authors of airgeddon. Yeah @jarilaos is right. From v8.11 now airgeddon can handle any card compatible with monitor mode even if it is not compatible to airmon. Happy hacking! 😸

**Comment by kimocoder** [comment]
It has been added anyway, the commit to aircrack-ng may be seen at https://github.com/aircrack-ng/aircrack-ng/commit/3cc9de5e7cbe6565c7e1fe12ebbcf2c6f7413c8d and at https://github.com/aircrack-ng/aircrack-ng/commit/b30a962ec20dc16501359c0aca21eda723e3f7ac

**Comment by v1s1t0r1sh3r3** [comment]
Great, any improvement or any new compatibility on aircrack is welcome! thanks for your work.

**Comment by ValZapod** [comment]
@kimocoder Have you read this https://wireless.wiki.kernel.org/en/users/documentation/iw#adding_interfaces_with_iw
I suppose this command is not working `iw phy phy0 interface add moni0 type monitor`.

**Comment by kimocoder** [comment]
ooooh no that won't work.. that's just to easy.
this is the output from the command:

ethtool failed...
Only mac80211 devices on kernel 2.6.33 or higher are officially supported by airmon-ng.

**Comment by ValZapod** [comment]
@kimocoder I suppose because it is not implemented in driver, as well as monitor flags, that is why this issue #240.

**Comment by ValZapod** [comment]
@kimocoder I find this in google https://www.wireshark.org/lists/wireshark-dev/201601/msg00066.html
"So it [the otherbss and control flag] will be set by default in most cases. However I can see that some other drivers do their own management in this area. So it is probably a good idea to set the flags anyway. Having a UI to manage the flags would be even better."

**Comment by kimocoder** [comment]
This is only going to happen if we move from nl80211/cfg80211 to mac80211. closing the issue.

**Comment by Medullitus** [comment]
Help please. I have the same chipset please help!!!

**Comment by Medullitus** [comment]
> This is only going to happen if we move from nl80211/cfg80211 to mac80211. closing the issue.

Helpppppp

**Comment by usama7628674** [comment]
@Medullitus No help can be provided unless you submit your plea to Realtek and they might consider your request and move from cfg80211 to mac80211.

**Comment by Medullitus** [comment]
> @Medullitus No help can be provided unless you submit your plea to Realtek and they might consider your request and move from cfg80211 to mac80211.

Why don't you do that? It seems you love talking too much!

**Comment by usama7628674** [comment]
@Medullitus They don't consider requests of outsiders. Maybe your desperation may cause them to change their stance.
