### ISSUE TITLE
TP-LINK AC600 - Monitor mode fine but Injection not working

### ISSUE THREAD

**Issue by c0d3l0g1c** [aircrack-ng/rtl8812au#931]
Bought a TP-LINK AC600 (Archer T2U) USB Wireless Adapter.

Monitor Mode works just fine, however, injection does not work.

```
root@kali:~# aireplay-ng --test wlan0
13:22:04  Trying broadcast probe requests...
13:22:05  No Answer...
13:22:05  Found 0 APs
```

Please help! Hours are flying bye... any suggestions?

**Comment by c0d3l0g1c** [comment]
Solution:

git clone -b v5.6.4.2 https://github.com/aircrack-ng/rtl8812au.git
cd rtl8812au
make RTL8811=1 DEBUG=1
sudo make install

**Comment by c0d3l0g1c** [comment]
After 100's of searches and trial and error found a solution that works for me on Klai Linux.

**Comment by zzzzz0001** [comment]
can you let us know your kali version?
also, are you using Virtualbox or any other virtual machine software?
