### ISSUE TITLE
Not a issue at all, just a "thanks": this is the only true rtl8812 driver repo that WORKS

### ISSUE THREAD

**Issue by terremoth** [aircrack-ng/rtl8812au#935]
You will find lots of "rtl8812au/bu" repos with drivers that most of them DOESN'T WORK, doesn't compile or you will do lot's of sh*t to try and won't work.

THIS IS THE ONLY TRUE REPO TO RULE THEM ALL

You can safely and easily use your wi-fi dongle now: doing as simple as this inside the clonned repo:

```sh
$ make
$ sudo make install
```

Btw, Idk why they don't do .deb/.rpm packeges with THIS! 

Wi-Fi drivers are one of the barriers for people not migrating from Windows to Linux! Thank you people responsible for this repo.

**Comment by morrownr** [comment]
Hi @terremoth 

> Wi-Fi drivers are one of the barriers for people not migrating from Windows to Linux!

Here is a good read:

https://github.com/morrownr/USB-WiFi

Regards
