### ISSUE TITLE
Needing Help. | How do i compile and install drivers on android?

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/rtl8812au#943]
Old Compilation issue for wifi antenna

**Comment by kimocoder** [comment]
Like I did here;

https://github.com/kimocoder/kernel_common/commit/859c386cc2d7dcfb30452949b92631f98ff35aa2


Just take it as a patch like this (in root Android kernel folder);
wget https://github.com/kimocoder/kernel_common/commit/859c386cc2d7dcfb30452949b92631f98ff35aa2.patch && patch -p1 < *. patch

**Comment by vaibhav423** [comment]
@kimocoder the page isnt available .
i tried to compile but after loading .ko it didnt work


[10150.086607] 88XXau: no symbol version for module_layout
[10150.086637] 88XXau: loading out-of-tree module taints kernel.

**Comment by ziyaniftaliev** [comment]
Hi. Can you tell me how to build the ALFA AWUS036ACH (RTL8812AU) driver for a Xiaomi Mi A3 running Android 11 LineageOS 18.1 with the official Kali Nethunter custom kernel?
