### ISSUE TITLE
pahole-flags.sh: not found

### ISSUE THREAD

**Issue by floringeambasu** [aircrack-ng/rtl8812au#946]
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.16.0-kali5-amd64/build M=/home/florin/Downloads/rtl8812au  modules
make[1]: Entering directory '/usr/src/linux-headers-5.16.0-kali5-amd64'
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali5-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali5-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali5-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali5-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali5-common/scripts/pahole-flags.sh: not found
make[1]: Leaving directory '/usr/src/linux-headers-5.16.0-kali5-amd64'
---------------------------------------------------------------------------
Visit https://github.com/aircrack-ng/rtl8812au for support/reporting issues
or check for newer versions (branches) of these drivers.                   

Any ideas?

**Comment by napolegend** [comment]
How u solved it
