### ISSUE TITLE
do not build on archlinux with linux 5.18.0

### ISSUE THREAD

**Issue by ilyapashuk** [aircrack-ng/rtl8812au#965]
hello

my system:

archlinux with latest updates, kernel Linux 5.18.0

installation method:
following aur package:
https://aur.archlinux.org/packages/rtl88xxau-aircrack-dkms-git

it uses dkms

build fails.

make.log hear:
[make.log](https://github.com/aircrack-ng/rtl8812au/files/8800313/make.log)

**Comment by iyanmv** [comment]
Duplicate of #964

I included the patches mentioned in the other issue in the PKGBUILD. Give it another try.

**Comment by ilyapashuk** [comment]
thank you, now module builds successfully and works.
