### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by bilIgates** [aircrack-ng/rtl8812au#984]
compilation error in arm64
please fix the code

make[1]: Entering directory '/out'
  CC [M]  /rtl8812au/core/rtw_cmd.o
error: unknown warning option '-Wno-cast-function-type'; did you mean '-Wno-bad-function-cast'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Werror=cast-function-type'; did you mean '-Werror=bad-function-cast'? [-Werror,-Wunknown-warning-option]
make[4]: *** [../scripts/Makefile.build:362: /rtl8812au/core/rtw_cmd.o] Error 1
make[3]: *** [/Makefile:1721: _module_/rtl8812au] Error 2
make[2]: *** [Makefile:146: sub-make] Error 2
make[1]: *** [Makefile:24: __sub-make] Error 2

**Comment by bilIgates** [comment]
kernel 4.14.180

**Comment by kimocoder** [comment]
Makefile updated. pull latest with "git pull" and re-build to fix. Tnx
