### ISSUE TITLE
[Android build] error: use of undeclared identifier 'IEEE80211_BAND_5GHZ'

### ISSUE THREAD

**Issue by seppzer0** [aircrack-ng/rtl8812au#991]
I've been trying to include rtl8812au drivers into the Android kernel, but I keep getting this error:

`../drivers/net/wireless/realtek/rtl8812au/os_dep/linux/ioctl_cfg80211.c:204:50: error: use of undeclared identifier 'IEEE80211_BAND_5GHZ'
        CHAN5G(15, 0),  CHAN5G(16, 0),  CHAN5G(17, 0),  CHAN5G(18, 0),
                                                        ^
../drivers/net/wireless/realtek/rtl8812au/os_dep/linux/ioctl_cfg80211.c:139:13: note: expanded from macro 'CHAN5G'
                .band                   = NL80211_BAND_5GHZ,            \
                                          ^
../drivers/net/wireless/realtek/rtl8812au/include/../os_dep/linux/ioctl_cfg80211.h:415:27: note: expanded from macro 'NL80211_BAND_5GHZ'
#define NL80211_BAND_5GHZ IEEE80211_BAND_5GHZ`

Looking over at ioctl_cfg80211.h doesn't give me much info.

I've tried doing some research by myself, but couldn't find anything useful other than similar issues with builds for old versions of CentOS.
So any help and/or advice where and what to look for would be appreciated.

Some info on my setup:
Build OS / kernel version -- `Ubuntu 22.04.1 LTS / 5.15.0-41-generic`
Android kernel version -- `4.4.302`
CC / CCX -- `clang / clang++`
Repository branch -- `v5.6.4.2`

**Comment by sepp0** [comment]
I've applied the following change to the Makefile:
```
ifeq ($(CONFIG_PLATFORM_ANDROID_ARM64), y)
# For this to work, change the "modules:" section is also needed, in order to build with CLANG.
# "$(MAKE) ARCH=$(ARCH) SUBARCH=$(ARCH) REAL_CC=${CC_DIR}/clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=$(CROSS_COMPILE) -C $(KSRC) M=$(shell pwd) O="$(KBUILD_OUTPUT)" modules"
```

..and now o get this:
```
../drivers/net/wireless/realtek/rtl8812au/core/rtw_ap.c:3877:13: error: no member named 'auth_len' in 'struct sta_info'; did you mean 'auth_seq'?
        if ((psta->auth_len != 0) && (psta->pauth_frame != NULL)) {
                   ^~~~~~~~
                   auth_seq
../drivers/net/wireless/realtek/rtl8812au/include/sta_info.h:390:15: note: 'auth_seq' declared here
        unsigned int auth_seq;
                     ^
../drivers/net/wireless/realtek/rtl8812au/core/rtw_ap.c:3877:38: error: no member named 'pauth_frame' in 'struct sta_info'
        if ((psta->auth_len != 0) && (psta->pauth_frame != NULL)) {
                                      ~~~~  ^
../drivers/net/wireless/realtek/rtl8812au/core/rtw_ap.c:3878:19: error: no member named 'pauth_frame' in 'struct sta_info'
                rtw_mfree(psta->pauth_frame, psta->auth_len);
                          ~~~~  ^
../drivers/net/wireless/realtek/rtl8812au/include/osdep_service.h:261:42: note: expanded from macro 'rtw_mfree'
#define rtw_mfree(pbuf, sz)             _rtw_mfree((pbuf), (sz))
                                                    ^~~~
../drivers/net/wireless/realtek/rtl8812au/core/rtw_ap.c:3878:38: error: no member named 'auth_len' in 'struct sta_info'; did you mean 'auth_seq'?
                rtw_mfree(psta->pauth_frame, psta->auth_len);
                                                   ^~~~~~~~
                                                   auth_seq
../drivers/net/wireless/realtek/rtl8812au/include/osdep_service.h:261:50: note: expanded from macro 'rtw_mfree'
#define rtw_mfree(pbuf, sz)             _rtw_mfree((pbuf), (sz))
                                                            ^
../drivers/net/wireless/realtek/rtl8812au/include/sta_info.h:390:15: note: 'auth_seq' declared here
        unsigned int auth_seq;
                     ^
../drivers/net/wireless/realtek/rtl8812au/core/rtw_ap.c:3879:9: error: no member named 'pauth_frame' in 'struct sta_info'
                psta->pauth_frame = NULL;
                ~~~~  ^
../drivers/net/wireless/realtek/rtl8812au/core/rtw_ap.c:3880:9: error: no member named 'auth_len' in 'struct sta_info'; did you mean 'auth_seq'?
                psta->auth_len = 0;
                      ^~~~~~~~
                      auth_seq
../drivers/net/wireless/realtek/rtl8812au/include/sta_info.h:390:15: note: 'auth_seq' declared here
        unsigned int auth_seq;
```

In the repo of the another RTL driver I found this issue:
https://github.com/Mange/rtl8192eu-linux-driver/issues/179
..and it says that in order for the problem to be resolved the `CONFIG_IOCTL_CFG80211` has to be defined.

However, based on the Makefile that is already done via the **-DCONFIG_IOCTL_CFG80211**:
```
ifeq ($(CONFIG_PLATFORM_ANDROID_ARM64), y)
# For this to work, change the "modules:" section is also needed, in order to build with CLANG.
...
EXTRA_CFLAGS += -DCONFIG_IOCTL_CFG80211 -DRTW_USE_CFG80211_STA_EVENT
...
```

Which means that I do not know the reason I get current errors.
Again, I am probably missing something, but currently I do not know where to look anymore.

**Comment by sepp0** [comment]
This is ridiculous.
I've spent too much time trying to resolve the issue by myself.

I've tried different clang versions (from 12 to latest 14), but the build simply throws the same error I mentioned in my previous message.

Here is the Makefile I use for the build.
[Makefile.txt](https://github.com/aircrack-ng/rtl8812au/files/9419320/Makefile.txt)

Please do provide some feedback.

**Comment by sepp0** [comment]
*Thank you for your time and help*.
